"""Write the LaTeX tabular bodies for Paper 4A from results/numbers.json.

Every number in these tables is a \\num{label} macro defined by collect_numbers.py,
never a literal, so run that script first (and after any label change). A model
row with no data for a given cell prints an en dash, and every table lists every
model in style.MODEL_COLORS order, so the tables do not change shape as open-model
results land; only their dashes fill in.

Output: ./tables/ (set TABLES_DIR to change)
"""
import json
import os

import collect_numbers as CN
import common as C
import style

TABLES_DIR = os.environ.get("TABLES_DIR", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "tables"))
MODEL_ORDER = list(style.MODEL_COLORS)
DECISION_MODELS = [m for m in MODEL_ORDER if not m.startswith("comparator")]

D3_TASKS = [("d3_conv_go_awry", "toxicity", "Derail."), ("d3_wiki_corpus", "power", "Power"),
            ("d3_emotion", "emotion", "Emo."), ("d3_wiki_politeness", "politeness", "Pol.")]
NAMES_DATASETS = [("d1", "done", "D1"), ("d3_conv_go_awry", "toxicity", "Tox."),
                   ("d3_wiki_corpus", "power", "Pwr.")]

# Abbreviated row labels for the narrow, single-column tables (t04, t06, t07), where
# style.MODEL_LABELS is too wide to fit one ACL column even with every dataset column
# abbreviated. t03 and t05 are table* (full width) and use the full labels.
SHORT_LABEL = {"jev-1.13.0": "Jev", "laya-en": "Laya-EN", "laya-ml": "Laya-ML",
               "kev-0.8b": "Kev-S", "kev-9b": "Kev-L", "decider-2b": "Decider",
               "this-that-1.0": "ThisThat", "nimble-9b": "Nimble",
               "comparator-open": "Comp-open"}

NUM = None


def load_numbers():
    global NUM
    p = os.path.join(C.RESULTS, "numbers.json")
    NUM = json.load(open(p, encoding="utf-8"))


def has(label):
    return label in NUM and NUM[label].get("value") is not None


def cell(label):
    return "\\num{%s}" % label if has(label) else "--"


def write(name, lines):
    os.makedirs(TABLES_DIR, exist_ok=True)
    path = os.path.join(TABLES_DIR, name)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"  wrote {path}")
    return path


HEADER = ["% Generated by shared/src/t01_tables.py. Do not edit by hand.",
          "% Every numeric cell is a num-macro from numbers.tex; -- means that",
          "% model has no result for this cell yet."]


def t03_headline():
    """table*, ten columns: model, D1, D2, the four D3 tasks, D3 macro-F1, D1 soft,
    D2 out-of-scope AUROC."""
    d3_header = " & ".join(lab for _c, _s, lab in D3_TASKS)
    lines = HEADER + [
        "% Intended environment: table* (full ACL text width), \\small, booktabs.",
        "\\begin{tabular}{lccccccccc}",
        "\\toprule",
        f"Model & D1 & D2 & {d3_header} & D3 F1 & D1 soft & D2 AUROC \\\\",
        "\\midrule"]
    for m in DECISION_MODELS + ["comparator-open"]:
        ms = CN.SLUG[m]
        row = [style.MODEL_LABELS[m], cell(f"e1.{ms}.doneneutral.acc"), cell(f"e1.{ms}.dtwo.acc")]
        for _cond, cslug, _lab in D3_TASKS:
            row.append(cell(f"e1.{ms}.{cslug}.acc"))
        row.append(cell(f"e1.{ms}.dthree.macrofone"))
        row.append(cell(f"e1.{ms}.doneneutral.softacc"))
        row.append(cell(f"e1.{ms}.oos.auroc"))
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return write("t03_headline.tex", lines)


def t04_calibration():
    """One ACL column, six columns: model, dataset, ECE shipped/raw/scaled, coverage
    at 5% risk. Rows are model by dataset (D1, D2, D3 pooled) rather than one wide
    row per model, so it fits one column at \\small."""
    lines = HEADER + [
        "% Intended environment: single column, \\small, booktabs.",
        "% Model column uses the abbreviations of t01_tables.SHORT_LABEL; spell them",
        "% out once in the caption, e.g. Kev-S/Kev-L for Kev-0.8B/Kev-9B. Ship, Raw,",
        "% Scal. and Cov5 are ECE shipped/raw/scaled and coverage at 5% risk.",
        "{\\setlength{\\tabcolsep}{3pt}",
        "\\begin{tabular}{llrrrr}",
        "\\toprule",
        "Model & Set & Ship & Raw & Scal. & Cov5 \\\\",
        "\\midrule"]
    dsets = [("doneneutral", "D1"), ("dtwo", "D2"), ("dthree", "D3")]
    for m in DECISION_MODELS + ["comparator-open"]:
        ms = CN.SLUG[m]
        for dslug, dlab in dsets:
            p = f"e1.{ms}.{dslug}"
            row = [SHORT_LABEL[m], dlab, cell(f"{p}.ece"), cell(f"{p}.eceraw"),
                   cell(f"{p}.ecescaled"), cell(f"{p}.covfive")]
            lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}}"]
    return write("t04_calibration.tex", lines)


def t05_cardinality():
    """table*, eight columns: model, accuracy at K in (5, 20, 50, 150), ECE at 150,
    hierarchical accuracy, and the accuracy drop from 5 to 150 options."""
    lines = HEADER + [
        "% Intended environment: table* (full ACL text width), \\small, booktabs.",
        "\\begin{tabular}{lccccccc}",
        "\\toprule",
        "Model & Acc.\\,5 & Acc.\\,20 & Acc.\\,50 & Acc.\\,150 & ECE\\,150 & Hier. & Drop \\\\",
        "\\midrule"]
    for m in DECISION_MODELS:
        ms = CN.SLUG[m]
        p = f"e3.{ms}"
        row = [style.MODEL_LABELS[m], cell(f"{p}.five.acc"), cell(f"{p}.twenty.acc"),
               cell(f"{p}.fifty.acc"), cell(f"{p}.all.acc"), cell(f"{p}.all.ece"),
               cell(f"{p}.hier.acc"), cell(f"{p}.drop")]
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return write("t05_cardinality.tex", lines)


def t06_names():
    """One ACL column, seven columns: model, dataset, flips per hundred for 0/1,
    random strings and swapped, the aligned AUC, and the test-retest floor."""
    lines = HEADER + [
        "% Intended environment: single column, \\small, booktabs.",
        "% Model column uses the abbreviations of t01_tables.SHORT_LABEL.",
        "{\\setlength{\\tabcolsep}{3pt}",
        "\\begin{tabular}{llrrrrr}",
        "\\toprule",
        "Model & Set & 0/1 & Rand. & Swap & AUC & Floor \\\\",
        "\\midrule"]
    for m in DECISION_MODELS:
        ms = CN.SLUG[m]
        for _cond, dslug, dlab in NAMES_DATASETS:
            p = f"e2.{ms}.{dslug}"
            row = [SHORT_LABEL[m], dlab, cell(f"{p}.k01.flips"), cell(f"{p}.krand.flips"),
                   cell(f"{p}.kswap.flips"), cell(f"{p}.kny.auc"), cell(f"{p}.floor")]
            lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}}"]
    return write("t06_names.tex", lines)


def t07_cost():
    """One ACL column, five columns: model, hardware, USD per 1,000 decisions,
    p50 and p95 latency in ms, all on d1_neutral."""
    lines = HEADER + [
        "% Intended environment: single column, \\small, booktabs.",
        "% Model column uses the abbreviations of t01_tables.SHORT_LABEL.",
        "{\\setlength{\\tabcolsep}{3pt}",
        "\\begin{tabular}{llrrr}",
        "\\toprule",
        "Model & Hardware & USD/1k & p50 ms & p95 ms \\\\",
        "\\midrule"]
    for m in DECISION_MODELS + ["comparator-open"]:
        ms = CN.SLUG[m]
        p = f"e5.{ms}.d1neutral"
        hw = "API" if m == "jev-1.13.0" else "Colab GPU"
        row = [SHORT_LABEL[m], hw if has(f"{p}.pfifty") else "--", cell(f"{p}.usd"),
               cell(f"{p}.pfifty"), cell(f"{p}.pninetyfive")]
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}}"]
    return write("t07_cost.tex", lines)


def t08_cascade():
    """Confidence-gated cascades on D1 (typed-decisions) and D2 (CLINC-150): every decision
    model first with the open generative comparator second, then every open decision model
    first with the hosted model second. Columns are the two single-stage accuracies, the
    best cascade accuracy over the threshold sweep, the escalated share at that point and
    its cost fraction (Equation costfraction)."""
    lines = HEADER + [
        r"% Intended environment: table* (full width), \small, booktabs.",
        r"{\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{llrrrrrrrrrr}",
        r"\toprule",
        r" & & \multicolumn{5}{c}{D1 typed-decisions} & \multicolumn{5}{c}{D2 CLINC-150} \\",
        r"\cmidrule(lr){3-7}\cmidrule(lr){8-12}",
        r"First & Second & First & Second & Cascade & Esc. & Cost & First & Second & Cascade & Esc. & Cost \\",
        r"\midrule"]
    pairs = [(m, "comparator-open") for m in MODEL_ORDER if m != "comparator-open"]
    pairs += [(m, "jev-1.13.0") for m in MODEL_ORDER if m not in ("jev-1.13.0", "comparator-open")]
    for f, s2 in pairs:
        fs, ss = CN.SLUG[f], CN.SLUG[s2]
        row = [SHORT_LABEL[f], SHORT_LABEL[s2]]
        for cs in ("doneneutral", "dtwo"):
            p = f"e6.{fs}.{ss}.{cs}"
            for m in ("accfirst", "accsecond", "hoacc", "hoescalated", "hocostfraction"):
                row.append(cell(f"{p}.{m}"))
        lines.append(" & ".join(row) + r" \\")
        if (f, s2) == pairs[len(DECISION_MODELS) - 1]:
            lines.append(r"\midrule")
    lines += [r"\bottomrule", r"\end{tabular}}"]
    return write("t08_cascade.tex", lines)


# ----------------------------------------------------------------------------------------
# EAAI mode (python t01_tables.py --eaai). Writes the redesigned tables of the journal
# version to EAAI_TABLES_DIR in the visual system of paper4a_tables.sty: a green header
# band, family group rows, model swatches in the figure palette, bold best values and
# symbol markers computed here from numbers.json at printed precision. Every numeric
# cell shows the same \num label as the ACL table of the same name; eaai_main() checks
# that against the ACL files before it returns. The default mode above is unchanged.

EAAI_TABLES_DIR = os.environ.get("EAAI_TABLES_DIR", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "tables_eaai"))

FAMILIES = [("Hosted", ["jev-1.13.0"]),
            ("Open, encoder head", ["laya-en", "laya-ml"]),
            ("Open, decoder head", ["kev-0.8b", "kev-9b", "decider-2b", "this-that-1.0",
                                    "nimble-9b"]),
            ("Generative comparator", ["comparator-open", "comparator-open2",
                                       "comparator-open2-ll", "comparator-open2-think",
                                       "comparator-gemma", "comparator-gemma-ll",
                                       "comparator-mistral", "comparator-mistral-ll"])]
# base checkpoint of each comparator readout; family_rows leaves a small gap between bases
COMP_BASE = {"comparator-open": "qwen3", "comparator-open2": "qwen36",
             "comparator-open2-ll": "qwen36", "comparator-open2-think": "qwen36",
             "comparator-gemma": "gemma", "comparator-gemma-ll": "gemma",
             "comparator-mistral": "mistral", "comparator-mistral-ll": "mistral"}
WORDS = {2: "two", 3: "three", 4: "four", 5: "five", 6: "six", 7: "seven", 8: "eight",
         9: "nine", 10: "ten", 11: "eleven", 12: "twelve", 13: "thirteen"}

EAAI_HEADER = ["% Generated by shared/src/t01_tables.py. Do not edit by hand.",
               "% Every numeric cell is a num-macro from numbers.tex; -- means that",
               "% model has no result for this cell yet. Needs paper4a_tables.sty."]


def printed(label):
    """The value of a label as the manuscript prints it, as a float, or None."""
    if not has(label):
        return None
    rec = NUM[label]
    v = rec["value"]
    if isinstance(v, str):
        return None
    fmt = rec.get("fmt")
    return float(format(v, fmt)) if fmt else float(v)


def best_of(labels, mode):
    """Labels holding the best printed value (max or min); ties are all returned."""
    # Laya (multilingual) on the full intent list works on truncated option keys (its
    # option text exceeds the input budget), so its cells there are shown but not ranked
    vals = {l: printed(l) for l in labels
            if not ("layaml" in l and ("dtwo" in l or "d2k150" in l or l.startswith("e3.")))}
    vals = {l: v for l, v in vals.items() if v is not None}
    if not vals:
        return set()
    b = max(vals.values()) if mode == "max" else min(vals.values())
    return {l for l, v in vals.items() if v == b}


def ecell(label, best=(), mark=None, slot=False):
    """A numeric cell: \\num{label}, bold when best, with an optional marker slot."""
    if not has(label):
        s = "--"
    else:
        s = "\\num{%s}" % label
        if label in best:
            s = "\\best{%s}" % s
    if slot:
        s += "\\mk{%s}" % (mark or "")
    return s


def mname(m):
    return "\\msw{%s}%s" % (CN.SLUG[m], style.MODEL_LABELS[m])


def groupspan(ncols, label):
    return "\\groupspan{%s}{%s}" % (WORDS[ncols], label)


def colspec(parts):
    """parts: list of (type, fraction). The fractions must sum to one, so the band and
    the rules span \\linewidth exactly."""
    total = sum(f for _t, f in parts)
    assert abs(total - 1.0) < 1e-9, total
    return "".join("%s{%.4f}" % (t, f) for t, f in parts)


def with_tabhead(lines):
    """Insert \\tabhead after the \\midrule that closes each header block (a \\midrule that
    directly follows a \\headrow line). It expands to nothing in a tabular and to \\endhead
    in an appendix longtable (\\longtab in paper4a_tables.sty)."""
    out = []
    for i, l in enumerate(lines):
        out.append(l)
        if l.strip() == "\\midrule" and i and lines[i - 1].lstrip().startswith("\\headrow"):
            out.append("\\tabhead")
    return out


def keep_last_rows(lines, n=3):
    """End the last n body rows before each \\bottomrule with \\\\* instead of \\\\, so a
    longtable never leaves one or two rows alone on a new page (in a tabular \\\\* is the same
    as \\\\)."""
    out = list(lines)
    for i, l in enumerate(out):
        if l.strip() != "\\bottomrule":
            continue
        k, j = 0, i - 1
        while j >= 0 and k < n and not out[j].lstrip().startswith(("\\midrule", "\\tabhead")):
            if out[j].rstrip().endswith(" \\\\"):
                out[j] = out[j].rstrip() + "*"
                k += 1
            j -= 1
    return out


def ewrite(name, lines):
    lines = keep_last_rows(with_tabhead(lines))
    os.makedirs(EAAI_TABLES_DIR, exist_ok=True)
    path = os.path.join(EAAI_TABLES_DIR, name)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"  wrote {path}")
    return path


def family_rows(models, ncols, row_fn, between=None):
    """Group rows by model family, skipping families with no model in `models`;
    `between` is a line put between two models of the same family."""
    out = []
    for fam, members in FAMILIES:
        ms = [m for m in members if m in models]
        if not ms:
            continue
        if len(ms) > 1 and fam.endswith("comparator"):
            fam += "s"
        out.append(groupspan(ncols, fam))
        for i, m in enumerate(ms):
            if between and i:
                out.append(between)
            elif i and m in COMP_BASE and COMP_BASE[m] != COMP_BASE.get(ms[i - 1]):
                out.append("\\addlinespace[2.5pt]")
            out += row_fn(m)
    return out



def e_t16_scores():
    """Appendix. Multi-class Brier score and negative log-likelihood of every model on each
    benchmark, as shipped. Bold is the lowest value in each column."""
    models = DECISION_MODELS + COMPARATORS_ALL
    dsets = [("doneneutral", "D1"), ("dtwo", "D2")] + [(cs, lab) for _c, cs, lab in D3_TASKS]
    cols = [(ds, met) for ds, _l in dsets for met in ("brier", "nll")]
    best = set()
    for ds, met in cols:
        best |= best_of([f"e1.{CN.SLUG[m]}.{ds}.{met}" for m in models], "min")

    def row(m):
        ms = CN.SLUG[m]
        return [" & ".join([mname(m)] + [ecell(f"e1.{ms}.{ds}.{met}", best) for ds, met in cols])
                + " \\\\"]

    n = 1 + len(cols)
    spec = colspec([("P", NAME_W)] + [("N", (1 - NAME_W) / len(cols))] * len(cols))
    words = {13: "thirteen"}
    groups = " & ".join("\\hdgroup{two}{%s}" % lab for _ds, lab in dsets)
    rules = ",".join("%d-%d" % (2 + 2 * i, 3 + 2 * i) for i in range(len(dsets)))
    subs = " & ".join("\\hdsub{Brier} & \\hdsub{NLL}" for _ in dsets)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\setlength{\\tabcolsep}{2pt}",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & %s \\\\" % groups,
        "\\bandrules{%s}" % rules,
        "\\headrow \\hdsub{Model} & %s \\\\" % subs,
        "\\midrule"]
    lines += family_rows(models, n, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Brier is the multi-class Brier score and NLL the negative log-likelihood"
              " of the reference label, both from the probabilities as shipped. Bold marks the"
              " lowest value in each column, with ties bolded, and the over-budget Laya"
              " (multilingual) cells on D2 are shown but not ranked.}"]
    return ewrite("t16_scores.tex", lines)

def e_t03_headline():
    """Full width. Columns grouped by dataset: D1 (accuracy, soft accuracy), D2 (accuracy,
    out-of-scope AUROC), D3 (four task accuracies, mean macro-F1). Bold is the best value
    of each column over every row."""
    models = DECISION_MODELS + COMPARATORS_ALL
    cols = [("acc", "doneneutral.acc"), ("soft", "doneneutral.softacc"),
            ("acc", "dtwo.acc"), ("auroc", "oos.auroc")]
    cols += [("acc", f"{cs}.acc") for _c, cs, _l in D3_TASKS] + [("f1", "dthree.macrofone")]
    # conventional classifiers: one row trained per task on its own labels (BGE-small
    # embeddings + logistic regression; BERT-base only on D2) and one zero-shot NLI row
    d3b = ["d3convgoawry", "d3wikicorpus", "d3emotion", "d3wikipoliteness"]
    bl_rows = [
        ("BGE-small, trained per task",
         ["bl.bgesmalllrd1.d1neutral.acc", "bl.bgesmalllrd1.d1neutral.softacc",
          "bl.bgesmalllrclinc.d2k150.acc", "bl.bgesmalllrclinc.d2k150.aurocoos"]
         + [f"bl.bgesmalllrd3.{t}.acc" for t in d3b] + ["bl.bgesmalllrd3.dthree.macrofone"]),
        ("BERT-base, fine-tuned",
         [None, None, "bl.bertbaseclinc.d2k150.acc", "bl.bertbaseclinc.d2k150.aurocoos"]
         + [None] * 5),
        ("DeBERTa-v3-large, fine-tuned",
         ["bl.debertalarged1.d1neutral.acc", "bl.debertalarged1.d1neutral.softacc",
          "bl.debertalargeclinc.d2k150.acc", "bl.debertalargeclinc.d2k150.aurocoos"]
         + [f"bl.debertalarged3.{t}.acc" for t in d3b] + ["bl.debertalarged3.dthree.macrofone"]),
        ("DeBERTa-v3 NLI, zero-shot",
         ["bl.nlidebertav3base.d1neutral.acc", "bl.nlidebertav3base.d1neutral.softacc",
          "bl.nlidebertav3base.d2k150.acc", "bl.nlidebertav3base.d2k150.aurocoos"]
         + [f"bl.nlidebertav3base.{t}.acc" for t in d3b]
         + ["bl.nlidebertav3base.dthree.macrofone"]),
    ]
    best = set()
    for j, (_k, suf) in enumerate(cols):
        pool = [f"e1.{CN.SLUG[m]}.{suf}" for m in models]
        pool += [labs[j] for _n, labs in bl_rows if labs[j] and has(labs[j])]
        best |= best_of(pool, "max")

    def row(m):
        ms = CN.SLUG[m]
        name = "\\msw{%s}%s" % (ms, COMPARATOR_ROWS[m]) if m in COMPARATOR_ROWS else mname(m)
        return [" & ".join([name] + [ecell(f"e1.{ms}.{suf}", best) for _k, suf in cols])
                + " \\\\"]

    def bl_row(name, labs):
        cells = [name] + [ecell(l, best) if l and has(l) else "--" for l in labs]
        return " & ".join(cells) + " \\\\"

    spec = colspec([("P", NAME_W)] + [("N", (1 - NAME_W) / 9)] * 9)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & \\hdgroup{two}{D1 typed-decisions} & \\hdgroup{two}{D2 CLINC-150}"
        " & \\hdgroup{five}{D3 social science tasks} \\\\",
        "\\bandrules{2-3,4-5,6-10}",
        "\\headrow \\hdsub{Model} & \\hdsub{Acc.} & \\hdsub{Soft} & \\hdsub{Acc.} & \\hdsub{AUROC}"
        " & \\hdsub{Derail.} & \\hdsub{Power} & \\hdsub{Emotion} & \\hdsub{Polite.}"
        " & \\hdsub{F1} \\\\",
        "\\midrule"]
    lines += family_rows(models, 10, row)
    lines += ["\\groupspan{ten}{Classifier trained on each task's own labels}",
              bl_row(*bl_rows[0]), bl_row(*bl_rows[1]), bl_row(*bl_rows[2]),
              "\\groupspan{ten}{Zero-shot classifier}", bl_row(*bl_rows[3])]
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Acc.\\ is accuracy, Soft is agreement with the teacher distribution,"
              " AUROC separates in-scope from out-of-scope inputs, and F1 is the mean macro-F1"
              " of the four D3 tasks in percent. The trained classifiers use labeled data of each"
              " task disjoint from its test items, and the decision models and the comparators use no task"
              " training except where Section~\\ref{sec:models} states it. Bold marks the best"
              " value in each column over all rows, with ties bolded.}"]
    return ewrite("t03_headline.tex", lines)


def e_t04_calibration():
    """Full width, one row per model, a column group per dataset with ECE shipped, raw and
    scaled and coverage at the stated risk. Bold is the lowest ECE and the highest coverage
    of each column; a triangle marks a shipped ECE above the raw ECE, where the stored
    temperature raises the error."""
    models = DECISION_MODELS + COMPARATORS_ALL
    dsets = ["doneneutral", "dtwo", "dthree"]
    metrics = [("ece", "min"), ("eceraw", "min"), ("ecescaled", "min"), ("covfive", "max")]
    best = set()
    for ds in dsets:
        for met, mode in metrics:
            # the raw arm exists only where rv.raw.<model>.available says so (a09 section C)
            pool = [m for m in models if met != "eceraw" or raw_ok(m)]
            best |= best_of([f"e1.{CN.SLUG[m]}.{ds}.{met}" for m in pool], mode)

    def row(m):
        ms = CN.SLUG[m]
        cells = [mname(m)]
        for ds in dsets:
            p = f"e1.{ms}.{ds}"
            # the marker compares unrounded values, so a rise hidden by rounding still shows
            ship = NUM[f"{p}.ece"]["value"] if printed(f"{p}.ece") is not None else None
            raw = (NUM[f"{p}.eceraw"]["value"]
                   if raw_ok(m) and printed(f"{p}.eceraw") is not None else None)
            up = ship is not None and raw is not None and ship > raw
            cells.append(ecell(f"{p}.ece", best, "\\mkup" if up else None, slot=True))
            cells += [ecell(f"{p}.eceraw", best) if raw_ok(m) else "--",
                      ecell(f"{p}.ecescaled", best), ecell(f"{p}.covfive", best)]
        return [" & ".join(cells) + " \\\\"]

    rest = (1.0 - NAME_W - 3 * 0.068) / 9
    spec = colspec([("P", NAME_W)] + ([("N", 0.068)] + [("N", rest)] * 3) * 3)
    lines = EAAI_HEADER + [
        "\\tablestylewide",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & \\hdgroup{four}{D1 typed-decisions} & \\hdgroup{four}{D2 CLINC-150}"
        " & \\hdgroup{four}{D3 pooled} \\\\",
        "\\bandrules{2-5,6-9,10-13}",
        "\\headrow \\hdsub{Model}" + (" & \\hdsub{Ship.\\mk{}} & \\hdsub{Raw} & \\hdsub{Scal.}"
                                     " & \\hdsub{Cov.}") * 3 + " \\\\",
        "\\midrule"]
    lines += family_rows(models, 13, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Ship., Raw and Scal.\\ are the expected calibration error as shipped,"
              " at a temperature of one and after scaling, and Cov.\\ is the coverage at"
              " \\num{p.riskfive} percent risk as shipped. The raw arm exists only where the"
              " served temperature is known and the temperature-one distribution is stored,"
              " so Jev 1.13.0 and the verbal readouts have none, and the likelihood readout is itself"
              " read at a temperature of one. The Laya (multilingual) cells on D2, whose option text"
              " exceeds its input budget, are shown but not ranked. Bold marks the lowest"
              " error and the highest coverage in each column, with ties bolded, and \\mkup\\"
              " marks a shipped error above the raw error before rounding, where the stored"
              " temperature raises the error.}"]
    return ewrite("t04_calibration.tex", lines)


def raw_ok(m):
    """True when the model has a raw (temperature-one) arm, per rv.raw.<model>.available."""
    lab = f"rv.raw.{CN.SLUG[m]}.available"
    return has(lab) and NUM[lab]["value"] == "yes"


def e_t05_cardinality():
    """Full width, one row per decision model: one-stage accuracy at the four option counts,
    ECE with all options, the exact two-stage accuracy and the drop from the smallest to
    the largest option set."""
    cols = [("five.acc", "max"), ("twenty.acc", "max"), ("fifty.acc", "max"),
            ("all.acc", "max"), ("all.ece", "min"), ("hier.acc", "max"), ("drop", "min")]
    models = DECISION_MODELS + [m for m in COMPARATORS_ALL if has(f"e3.{CN.SLUG[m]}.all.acc")]
    best = set()
    for suf, mode in cols:
        best |= best_of([f"e3.{CN.SLUG[m]}.{suf}" for m in models], mode)

    def row(m):
        ms = CN.SLUG[m]
        return [" & ".join([mname(m)] + [ecell(f"e3.{ms}.{suf}", best) for suf, _m in cols])
                + " \\\\"]

    spec = colspec([("P", NAME_W)] + [("N", (1 - NAME_W) / 7)] * 7)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & \\hdgroup{four}{One-stage accuracy by option count}"
        " & \\hdgroup{three}{With all \\num{p.kall} options} \\\\",
        "\\bandrules{2-5,6-8}",
        "\\headrow \\hdsub{Model} & \\hdsub{\\num{p.kfive}} & \\hdsub{\\num{p.ktwenty}}"
        " & \\hdsub{\\num{p.kfifty}} & \\hdsub{\\num{p.kall}} & \\hdsub{ECE}"
        " & \\hdsub{Two-stage} & \\hdsub{Drop} \\\\",
        "\\midrule"]
    lines += family_rows(models, 8, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Two-stage is the accuracy of asking the domain and then the"
              " intent, and Drop is the one-stage accuracy lost from \\num{p.kfive} to"
              " \\num{p.kall} options. The two-stage condition was run for the decision models"
              " only. Bold marks the highest accuracy and the lowest error"
              " and drop in each column, with ties bolded.}"]
    return ewrite("t05_cardinality.tex", lines)


def flip_glyph(flips, floor):
    """Three-level scale of flips in excess of the test-retest floor, per hundred decisions:
    below one (the order of the hosted model's own floor), one to ten, ten or more."""
    if flips is None:
        return ""
    excess = round(flips - (floor or 0.0), 1)    # flips and floors print to one decimal
    if excess < 1.0:
        return "\\symnone"
    if excess < 10.0:
        return "\\symhalf"
    return "\\symfull"


def e_t06_names():
    """Full width, one block of three rows (the binary sets) per decision model: flips per
    hundred against the aligned identifiers for digits, random strings and the swap, each
    with a glyph for its excess over the floor, the aligned AUC and the floor."""
    set_names = {"done": "Typed-decisions", "toxicity": "Derailment", "power": "Power"}
    models = DECISION_MODELS + [m for m in COMPARATORS_ALL
                                if has(f"e2.{CN.SLUG[m]}.done.kswap.flips")]
    best = set()
    for _c, ds, _l in NAMES_DATASETS:
        best |= best_of([f"e2.{CN.SLUG[m]}.{ds}.kny.auc" for m in models], "max")

    def row(m):
        ms = CN.SLUG[m]
        out = []
        for i, (_c, ds, _l) in enumerate(NAMES_DATASETS):
            p = f"e2.{ms}.{ds}"
            floor = printed(f"{p}.floor")
            cells = [mname(m) if i == 0 else "", set_names[ds]]
            for k in ("k01", "krand", "kswap"):
                lab = f"{p}.{k}.flips"
                cells.append("\\flipcell{%s}{%s}" % (flip_glyph(printed(lab), floor), ecell(lab))
                             if has(lab) else "\\flipcell{}{--}")
            cells += [ecell(f"{p}.kny.auc", best), ecell(f"{p}.floor")]
            out.append(" & ".join(cells) + " \\\\")
        return out

    spec = colspec([("P", NAME_W), ("P", 0.165)] + [("N", 0.11)] * 5)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & \\hdtop{} & \\hdgroup{three}{Flips per hundred decisions}"
        " & \\hdtop{} & \\hdtop{} \\\\",
        "\\bandrules{3-5}",
        "\\headrow \\hdsub{Model} & \\hdsub{Binary set} & \\hdsub{\\flipcell{}{Digits}}"
        " & \\hdsub{\\flipcell{}{Random}} & \\hdsub{\\flipcell{}{Swapped}} & \\hdsub{AUC}"
        " & \\hdsub{Floor} \\\\",
        "\\midrule"]
    lines += family_rows(models, 7, row, between="\\addlinespace[2.5pt]")
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Digits, Random and Swapped are the option-name conditions, AUC is"
              " measured under the aligned identifiers and Floor is the test-retest floor. The"
              " glyph grades the flips above the model's floor on that set, \\symnone\\ below"
              " one per hundred, \\symhalf\\ from one to ten and \\symfull\\ ten or more."
              " A floor that was not measured counts as zero, as it is for every open"
              " model on typed-decisions and for every comparator. Bold marks the highest AUC on each set, with ties bolded.}"]
    return ewrite("t06_names.tex", lines)


def e_t07_cost():
    """Full width: platform, cost per thousand decisions with an inline bar on a linear
    scale to the most expensive model and a tick at the hosted list price, and the median
    and tail latency. Bold is the lowest value of each column."""
    models = DECISION_MODELS + COMPARATORS_ALL

    def lat(m):
        # comparators: latency of the runs with one request at a time (the -b1 tags); their
        # batched runs give the cost
        ms = CN.SLUG[m]
        return f"e5.{ms}bone.d1neutral" if m in COMPARATORS_ALL else f"e5.{ms}.d1neutral"
    usd = [f"e5.{CN.SLUG[m]}.d1neutral.usd" for m in models]
    best = best_of(usd, "min")
    for suf in ("pfifty", "pninetyfive"):
        best |= best_of([f"{lat(m)}.{suf}" for m in models], "min")
    # the scale ends at the most expensive model other than the thinking mode, whose bar is cut
    have = [l for l in usd if printed(l) is not None and "think" not in l]
    top = max(have, key=printed)
    ref = "e5.jev.d1neutral.usd"

    def row(m):
        ms = CN.SLUG[m]
        p = f"e5.{ms}.d1neutral"
        hw = ("API" if m == "jev-1.13.0" else "Colab A100"
              if m in COMPARATORS_ALL and m != "comparator-open" else "Colab L4")
        bar = "\\valbar{%s.usd}{%s}{%s}" % (p, top, ref) if has(f"{p}.usd") else ""
        return [" & ".join([mname(m), hw if has(f"{p}.usd") else "--",
                            ecell(f"{p}.usd", best), bar, ecell(f"{lat(m)}.pfifty", best),
                            ecell(f"{lat(m)}.pninetyfive", best)]) + " \\\\"]

    bar_frac = 0.24
    spec = colspec([("P", NAME_W), ("P", 0.13), ("N", 0.105), ("P", bar_frac),
                    ("N", 0.12), ("N", 0.12)])
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\setlength{\\valbarwidth}{\\dimexpr%.4f\\linewidth-2\\tabcolsep\\relax}" % bar_frac,
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & \\hdtop{} & \\hdgroup{two}{US dollars per thousand decisions}"
        " & \\hdgroup{two}{Latency in ms} \\\\",
        "\\bandrules{3-4,5-6}",
        "\\headrow \\hdsub{Model} & \\hdsub{Measured on} & \\hdsub{Cost} & \\hdsub{}"
        " & \\hdsub{Median} & \\hdsub{\\num{p.pninetyfive}th pct.} \\\\",
        "\\midrule"]
    lines += family_rows(models, 6, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Costs of the comparators come from batched runs and their latencies"
              " from \\num{p.bone.requests} requests sent one at a time, with Gemma-4-31B and"
              " Mistral-Small-24B served without graph compilation and the thinking mode not"
              " timed alone. Bars share one linear scale, cut at its end for the thinking mode,"
              " and the orange tick marks the hosted model's list price. Bold marks the lowest"
              " value in each column, with ties bolded.}"]
    return ewrite("t07_cost.tex", lines)


def e_t08_cascade(blocks=None, fname="t08_cascade.tex"):
    """Full width, two stacked panels (D1 typed-decisions at decision level, D2 CLINC-150),
    one row per first stage grouped by the second stage. Cells come from rv.cas (a09 section
    D: out-of-fold thresholds, itemwise costs, cluster-bootstrap intervals that refit the
    thresholds). The single-stage accuracies are the e6 labels, which equal the
    acc_first/acc_second of revision_stats.json on the same aligned decisions (asserted
    below). A dot marks a gain whose interval excludes zero at printed precision."""
    rv = json.load(open(os.path.join(C.RESULTS, "revision_stats.json"), encoding="utf-8"))
    pairs = rv["D_cascades"]["pairs"]
    if blocks is None:
        blocks = [("Escalation to Gemma-4-31B, verbal", "comparator-gemma", DECISION_MODELS),
                  ("Escalation to Jev 1.13.0", "jev-1.13.0",
                   [m for m in DECISION_MODELS if m != "jev-1.13.0"])]
    panels = [("D1 typed-decisions", "doneneutral", "d1_neutral"),
              ("D2 CLINC-150", "dtwo", "d2_k150")]
    spec = colspec([("P", 0.26), ("N", 0.085), ("N", 0.085), ("N", 0.085), ("P", 0.13),
                    ("N", 0.075), ("P", 0.11), ("N", 0.085), ("N", 0.085)])
    marked = []
    lines = EAAI_HEADER + ["\\tablestylewide"]
    for pi, (ptitle, cs, cond) in enumerate(panels):
        if pi:
            lines.append("\\par\\vspace{6pt}")
        lines += [
            "\\begin{tabular}{%s}" % spec,
            "\\toprule",
            "\\headrow \\hdtop{%s} & \\hdgroup{two}{Single stage}"
            " & \\hdgroup{four}{Cascade} & \\hdgroup{two}{Escalation} \\\\" % ptitle,
            "\\bandrules{2-3,4-7,8-9}",
            "\\headrow \\hdsub{First stage} & \\hdsub{First} & \\hdsub{Second}"
            " & \\hdsub{Accuracy} & \\hdsub{} & \\hdsub{Gain\\mk{}} & \\hdsub{}"
            " & \\hdsub{Esc.} & \\hdsub{Cost} \\\\",
            "\\midrule"]
        for label, second, firsts in blocks:
            lines.append(groupspan(9, label))
            for f in firsts:
                fs, ss = CN.SLUG[f], CN.SLUG[second]
                e6p, p = f"e6.{fs}.{ss}.{cs}", f"rv.cas.{fs}.{ss}.{cs}"
                key = f"{f}>{second}|{cond}"
                if key in pairs:
                    dl = pairs[key]["decision_level"]
                    for lab, ref in ((f"{e6p}.accfirst", dl["acc_first"]),
                                     (f"{e6p}.accsecond", dl["acc_second"])):
                        assert has(lab) and abs(NUM[lab]["value"] - ref) < 1e-12, lab
                lo, hi = printed(f"{p}.gainlo"), printed(f"{p}.gainhi")
                excl = lo is not None and hi is not None and (lo > 0 or hi < 0)
                if excl:
                    marked.append(p)
                cells = [mname(f), ecell(f"{e6p}.accfirst"), ecell(f"{e6p}.accsecond"),
                         ecell(f"{p}.acc"), ivcell(f"{p}.acc"),
                         ecell(f"{p}.gain", mark="\\symfull" if excl else None, slot=True),
                         ivcell(f"{p}.gain"), ecell(f"{p}.esc"), ecell(f"{p}.costfrac")]
                lines.append(" & ".join(cells) + " \\\\")
        lines += ["\\bottomrule", "\\end{tabular}"]
    mark_text = (" \\symfull\\ marks a gain whose interval excludes zero."
                 if marked else " No gain interval excludes zero.")
    lines += ["\\tablenote{First and Second are the accuracies of each stage alone, Accuracy is"
              " the cascade accuracy with thresholds chosen on data disjoint from the scored"
              " items, and Gain is its difference from the better single stage in points. Esc.\\"
              " is the escalated share and Cost the cost fraction from each decision's own"
              " cost, where the escalation unit on D1 is the decision, a request's cost is shared"
              " among its decisions and a comparator is charged per question. Brackets hold"
              " cluster bootstrap intervals at"
              " \\num{p.boot.level} percent whose \\num{p.boot.refitreps} replicates refit the"
              " thresholds, unadjusted for the number of cascades. A dash marks a pair without results,"
              " because Laya (English) refused the full intent list, and" + mark_text[0].lower()
              + mark_text[1:] + "}"]
    E_MARKS[fname] = marked
    return ewrite(fname, lines)


def e_t22_cascade_qwen():
    """Appendix. The held-out cascades of t08 toward the two Qwen comparators."""
    blocks = [("Escalation to Qwen3-14B, verbal", "comparator-open", DECISION_MODELS),
              ("Escalation to Qwen3.6-27B, verbal", "comparator-open2", DECISION_MODELS),
              ("Escalation to Qwen3.6-27B, likelihood", "comparator-open2-ll", DECISION_MODELS)]
    return e_t08_cascade(blocks, "t22_cascade_qwen.tex")


# Labels behind the bold cells and the markers of the new EAAI tables, for the report.
E_MARKS = {}


def ivcell(prefix, lo="lo", hi="hi"):
    """A muted interval [lo, hi] for a separate left-aligned column; empty when missing."""
    a, b = f"{prefix}{lo}", f"{prefix}{hi}"
    if not (has(a) and has(b)):
        return ""
    return "{\\scriptsize\\cellnote{[\\num{%s}, \\num{%s}]}}" % (a, b)


def stack(value_cell, prefix, lo="lo", hi="hi"):
    """A value with its muted interval on a second line of the same cell. The break is a new
    paragraph, so both lines keep the column's alignment (\\newline would add \\hfil and push
    the value to the left)."""
    iv = ivcell(prefix, lo, hi)
    return value_cell + ("\\par" + iv if iv and value_cell != "--" else "")


TASK_COLS = [("doneneutral", "D1"), ("dtwo", "D2"), ("toxicity", "Derail."),
             ("power", "Power"), ("emotion", "Emotion"), ("politeness", "Polite.")]


def e_t09_calib_tasks():
    """Per-task calibration: expected calibration error as shipped and after cross-fitted
    temperature scaling (rv.ts), with the refit bootstrap interval of the scaled error beneath
    it. Bold is the lowest shipped and the lowest scaled error of each column."""
    models = DECISION_MODELS + COMPARATORS_ALL
    best = set()
    for cs, _l in TASK_COLS:
        for met in ("ece", "ecescaled"):
            best |= best_of([f"rv.ts.{CN.SLUG[m]}.{cs}.{met}" for m in models], "min")
    E_MARKS["t09_calib_tasks.tex"] = sorted(best)

    def row(m):
        ms = CN.SLUG[m]
        cells = [mname(m)]
        for cs, _l in TASK_COLS:
            p = f"rv.ts.{ms}.{cs}"
            cells += [ecell(f"{p}.ece", best),
                      stack(ecell(f"{p}.ecescaled", best), f"{p}.ecescaled")]
        return [" & ".join(cells) + " \\\\"]

    spec = colspec([("P", 0.16)] + [("N", 0.047), ("Q", 0.093)] * 6)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\setlength{\\tabcolsep}{2pt}",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{}" + "".join(" & \\hdgroup{two}{%s}" % l for _c, l in TASK_COLS)
        + " \\\\",
        "\\bandrules{2-3,4-5,6-7,8-9,10-11,12-13}",
        "\\headrow \\hdsub{Model}" + " & \\hdsub{Ship.} & \\hdsub{Scaled}" * 6 + " \\\\",
        "\\midrule"]
    lines += family_rows(models, 13, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Ship.\\ is the expected calibration error as shipped and Scaled the"
              " error after temperature scaling, with one temperature per question type fitted"
              " on the calibration split for D1 and temperatures cross-fitted over item folds for"
              " the other tasks. Beneath each scaled error is its cluster bootstrap interval at"
              " \\num{p.boot.level} percent, whose \\num{p.boot.refitreps} replicates refit the"
              " temperatures. Bold marks the lowest error in each column, with ties bolded.}"]
    return ewrite("t09_calib_tasks.tex", lines)


def e_t10_selective():
    """Selective prediction at the lower risk target on D1 and D2: in-sample coverage with its
    bootstrap interval (rv.sel), and the held-out coverage, realized risk and its one-sided
    upper bound (rv.ho). Bold is the highest held-out coverage of each dataset."""
    models = DECISION_MODELS + COMPARATORS_ALL
    dsets = [("doneneutral", "D1 typed-decisions"), ("dtwo", "D2 CLINC-150")]
    best = set()
    for cs, _l in dsets:
        best |= best_of([f"rv.ho.{CN.SLUG[m]}.{cs}.five.cov" for m in models], "max")
    E_MARKS["t10_selective.tex"] = sorted(best)

    def row(m):
        ms = CN.SLUG[m]
        cells = [mname(m)]
        for cs, _l in dsets:
            s, h = f"rv.sel.{ms}.{cs}", f"rv.ho.{ms}.{cs}.five"
            cells += [stack(ecell(f"{s}.covfive"), f"{s}.covfive"), ecell(f"{h}.cov", best),
                      ecell(f"{h}.risk"), ecell(f"{h}.riskub")]
        return [" & ".join(cells) + " \\\\"]

    spec = colspec([("P", NAME_W)] + [("N", (1 - NAME_W) / 8)] * 8)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{}" + "".join(" & \\hdgroup{four}{%s}" % l for _c, l in dsets)
        + " \\\\",
        "\\bandrules{2-5,6-9}",
        "\\headrow \\hdsub{Model}" + (" & \\hdsub{In-sample} & \\hdsub{Held-out}"
                                     " & \\hdsub{Risk} & \\hdsub{Bound}") * 2 + " \\\\",
        "\\midrule"]
    lines += family_rows(models, 9, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{In-sample is the coverage at \\num{p.riskfive} percent risk with the"
              " threshold chosen on the scored decisions, with its cluster bootstrap interval"
              " at \\num{p.boot.level} percent beneath. Held-out applies a threshold chosen by the"
              " same rule on the calibration split for D1 and on the other item folds for D2."
              " Risk is the error rate of the decisions it accepts and Bound is the one-sided"
              " \\num{p.boot.level} percent Clopper-Pearson upper limit of that rate, with a"
              " dash where no decision is accepted. A coverage printed as zero can still"
              " accept a few decisions. Bold marks the highest held-out coverage on"
              " each dataset, with ties bolded.}"]
    return ewrite("t10_selective.tex", lines)


HOLM_ALPHA = 0.05   # stated in words in the table note, never printed


def e_t11_paired():
    """Paired accuracy differences with Jev (rv.pd): each model minus Jev in points on
    identical decisions, with the paired cluster bootstrap interval beneath. Bold where the
    Holm-adjusted p value, at printed precision, is below HOLM_ALPHA."""
    models = [m for m in DECISION_MODELS if m != "jev-1.13.0"] + COMPARATORS_ALL

    def pref(m, cs):
        return f"rv.pd.{CN.SLUG[m]}.{cs}"

    sig = set()
    for m in models:
        for cs, _l in TASK_COLS:
            p = pref(m, cs)
            h = printed(f"{p}.holm")
            if h is not None and h < HOLM_ALPHA:
                sig.add(f"{p}.diff")
    E_MARKS["t11_paired.tex"] = sorted(sig)

    def row(m):
        ms = CN.SLUG[m]
        cells = ["\\msw{%s}%s" % (ms, COMPARATOR_ROWS[m]) if m in COMPARATOR_ROWS else mname(m)]
        for cs, _l in TASK_COLS:
            p = pref(m, cs)
            cells.append(stack(ecell(f"{p}.diff", sig), f"{p}.diff"))
        return [" & ".join(cells) + " \\\\"]

    spec = colspec([("P", NAME_W)] + [("N", (1 - NAME_W) / 6)] * 6)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & \\hdgroup{two}{Workflow and intent sets}"
        " & \\hdgroup{four}{D3 social science tasks} \\\\",
        "\\bandrules{2-3,4-7}",
        "\\headrow \\hdsub{Model}" + "".join(" & \\hdsub{%s}" % l for _c, l in TASK_COLS)
        + " \\\\",
        "\\midrule"]
    lines += family_rows(models, 7, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Each cell is the accuracy of the model minus that of Jev 1.13.0 on"
              " identical decisions in percentage points, with its paired cluster bootstrap"
              " interval at \\num{p.boot.level} percent over \\num{p.boot.pairedreps} replicates"
              " beneath. Bold marks a difference that is significant after Holm correction"
              " across the models of each dataset at the five percent level.}"]
    return ewrite("t11_paired.tex", lines)


# width of the model-name column, wide enough for the longest comparator label
NAME_W = 0.285

COMPARATORS_ALL = ["comparator-open", "comparator-open2", "comparator-open2-ll",
                   "comparator-open2-think", "comparator-gemma", "comparator-gemma-ll",
                   "comparator-mistral", "comparator-mistral-ll"]
COMPARATOR_ROWS = {m: style.MODEL_LABELS[m] for m in COMPARATORS_ALL}

# decision model -> (backbone slug, backbone name), following bench.BACKBONE_OF
BACKBONE_ROWS = [("kev-0.8b", "bbsmallbase", "Qwen3.5-0.8B-Base"),
                 ("kev-9b", "bbninebase", "Qwen3.5-9B-Base"),
                 ("nimble-9b", "bbnine", "Qwen3.5-9B"),
                 ("decider-2b", "bbtwobase", "Qwen3.5-2B-Base"),
                 ("this-that-1.0", "bbtwobase", "Qwen3.5-2B-Base")]


def e_t17_backbones():
    """Appendix. Each open decision model with a decoder head against the untuned backbone
    it adapts (a15, bb.*), in three stacked panels: the paired difference in accuracy and in
    shipped top-label calibration error, both in points, on D1, D2 and the four D3 tasks, and
    in flips per hundred under the swapped and the random-string option names on the three
    binary sets, with the interval beneath. Bold marks a difference significant after Holm
    correction across the five pairs of its column."""
    tasks = [("doneneutral", "D1"), ("dtwo", "D2"), ("toxicity", "Derail."),
             ("power", "Power"), ("emotion", "Emotion"), ("politeness", "Polite.")]
    names = [("donekswap", "D1 swap"), ("donek01", "D1 digits"), ("donekrand", "D1 rand."),
             ("toxicitykswap", "Derail. swap"), ("toxicitykrand", "Derail. rand."),
             ("powerkswap", "Power swap")]
    panels = [("Accuracy difference", [(c, "acc", l) for c, l in tasks]),
              ("Calibration error difference", [(c, "ece", l) for c, l in tasks]),
              ("Flip difference under option names", [(c, "flips", l) for c, l in names])]
    sig = set()
    for m, bs, _n in BACKBONE_ROWS:
        for _t, cols in panels:
            for c, met, _l in cols:
                p = f"bb.{CN.SLUG[m]}.{bs}.{c}.{met}"
                h = printed(f"{p}.holm")
                if h is not None and h < HOLM_ALPHA:
                    sig.add(f"{p}.diff")
    E_MARKS["t17_backbones.tex"] = sorted(sig)
    spec = colspec([("P", 0.15), ("P", 0.16)] + [("N", 0.115)] * 6)
    lines = EAAI_HEADER + ["\\tablestylewide"]
    for pi, (title, cols) in enumerate(panels):
        if pi:
            lines.append("\\par\\vspace{6pt}")
        lines += [
            "\\begin{tabular}{%s}" % spec,
            "\\toprule",
            "\\headrow \\hdtop{} & \\hdtop{} & \\hdgroup{six}{%s} \\\\" % title,
            "\\bandrules{3-8}",
            "\\headrow \\hdsub{Decision model} & \\hdsub{Untuned backbone}"
            + "".join(" & \\hdsub{%s}" % l for _c, _m, l in cols) + " \\\\",
            "\\midrule"]
        for m, bs, bname in BACKBONE_ROWS:
            cells = [mname(m), bname]
            for c, met, _l in cols:
                p = f"bb.{CN.SLUG[m]}.{bs}.{c}.{met}"
                cells.append(stack(ecell(f"{p}.diff", sig), f"{p}."))
            lines.append(" & ".join(cells) + " \\\\")
        lines += ["\\bottomrule", "\\end{tabular}"]
    lines += ["\\tablenote{Each cell is the decision model minus the untuned backbone it adapts"
              " on identical decisions, in points of accuracy or of shipped top-label calibration"
              " error, or in flips per hundred decisions against the aligned names, with its"
              " paired cluster bootstrap interval beneath. The backbones are scored by the"
              " likelihood of each option key after a plain prompt. The decider-2b and"
              " this-that-model-1.0 checkpoints were trained on CLINC-150, and this-that-model-1.0"
              " is adapted from decider-2b. Bold marks a difference significant after Holm"
              " correction across the five pairs of its column at the five percent level.}"]
    return ewrite("t17_backbones.tex", lines)


MANIFEST_TEMP = {"jev-1.13.0": None, "laya-en": "m.laya.temp", "laya-ml": "m.laya.temp",
                 "kev-0.8b": "m.kev08b.temp", "kev-9b": "m.kev9b.temp",
                 "decider-2b": "m.decider.temp", "this-that-1.0": "m.thisthat.temp",
                 "nimble-9b": "m.nimble.temp", "comparator-open": "m.comparator.temp"}


def _tt(s):
    """Monospace identifier; a space inside it (package and version) does not break."""
    # a long repository name may break after a hyphen of its model name
    s = s.replace("_", "\\_").replace(" ", "~")
    if len(s) > 32:
        s = s.replace("-Instruct-", "-\\allowbreak Instruct-")
    return "\\texttt{%s}" % s


def _single(counter, what, model):
    """The one value of a run_manifest field; the manifest must hold exactly one."""
    vals = list(counter)
    assert len(vals) == 1, f"{model}: {what} is not unique in run_manifest.json: {vals}"
    return json.loads(vals[0])


def _dates(counter):
    """The run dates of a model as one date or a first-to-last range (a model whose
    conditions ran over several days, such as a later revision run)."""
    d = sorted(json.loads(v) for v in counter)
    return d[0] if len(d) == 1 else f"{d[0]} to {d[-1]}"


def dcell(d):
    """A date or a date range in the manifest, the range on two lines of its cell."""
    return " to\\par ".join(_tt(x) for x in d.split(" to "))


def e_t12_manifest():
    """Run manifest: repository or service identifier (adapters.py), resolved revision, served
    temperature and run date (results/run_manifest.json, one value per model, asserted), and
    the runtime with the package pins of build_notebook.py and the comparator's logged vLLM and
    torch versions. Identifiers, dates and versions are set in texttt, the served temperature
    is a num label."""
    import re
    import adapters as AD
    man = json.load(open(os.path.join(C.RESULTS, "run_manifest.json"), encoding="utf-8"))
    src = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "build_notebook.py"),
               encoding="utf-8").read()

    def pin(pat):
        v = sorted(set(re.findall(pat, src)))
        assert len(v) == 1, (pat, v)
        return v[0]
    torch = pin(r'"torch==([\d.]+)"')
    laya = pin(r'"laya==([\d.]+)"')
    tf_min = pin(r'"transformers>=([\d.]+),<\d+"')
    tf_pin = pin(r'"transformers==([\d.]+)"')
    thisthat_sha = pin(r'THISTHAT_SHA = "([0-9a-f]{40})"')
    log = open(os.path.join(C.ANSWERS, "comparator-open", "comparator_log.txt"),
               encoding="utf-8", errors="replace").read()
    vv = sorted(set(re.findall(r"^vllm (\S+) torch (\S+?)(?:\+\S+)?$", log, re.M)))
    assert len(vv) == 1, vv
    vllm, ctorch = vv[0]
    kev_sha = AD.KEV_GITHUB_COMMIT

    repo = {"jev-1.13.0": "TypeSafe API, model " + _tt("jev-1.13.0"),
            "laya-en": _tt(AD.LAYA_REPO),
            "laya-ml": _tt(AD.LAYA_REPO) + ", subfolder " + _tt("multilingual"),
            "kev-0.8b": _tt(AD.KEV_REPOS["kev-0.8b"]), "kev-9b": _tt(AD.KEV_REPOS["kev-9b"]),
            "decider-2b": _tt(AD.DECIDER_REPO), "this-that-1.0": _tt(AD.THISTHAT_REPO),
            "nimble-9b": _tt(AD.NIMBLE_REPO), "comparator-open": _tt(AD.COMPARATOR_REPO)}
    colab = ""   # every open model and the comparator ran on a Colab L4, stated in the note
    tfpin = ", " + _tt("transformers>=" + tf_min)
    torchkev = colab + _tt("torch " + torch) + ", " + _tt("kev@" + kev_sha[:10])
    env = {"jev-1.13.0": "hosted service through " + _tt("typesafe_sdk"),
           "laya-en": colab + _tt("laya " + laya) + ", " + _tt("torch " + torch),
           "laya-ml": colab + _tt("laya " + laya) + ", " + _tt("torch " + torch),
           "kev-0.8b": torchkev + tfpin, "kev-9b": torchkev + tfpin,
           "decider-2b": torchkev + tfpin,
           "this-that-1.0": torchkev + tfpin + ", " + _tt("thisthat@" + thisthat_sha[:10]),
           "nimble-9b": colab + _tt("torch " + torch) + ", " + _tt("transformers " + tf_pin),
           "comparator-open": colab + _tt("vllm " + vllm) + ", " + _tt("torch " + ctorch)}

    def row(m):
        d = man[m]
        rev = _single(d["revision"], "revision", m)
        date = _dates(d["run_date"])
        temp = _single(d["served_temperature"], "served_temperature", m)
        assert _single(d["model_returned"], "model_returned", m)
        tl = MANIFEST_TEMP[m]
        if tl is None:
            assert temp is None, m
            tcell = "--"
        else:
            assert temp is not None and abs(float(format(temp, NUM[tl]["fmt"] or ".2f"))
                                            - printed(tl)) < 1e-9, (m, temp)
            tcell = ecell(tl)
        is_hex = bool(re.fullmatch(r"[0-9a-f]{40}", str(rev)))
        assert is_hex or m == "jev-1.13.0", (m, rev)
        return [" & ".join([mname(m), repo[m], _tt(rev[:10]) if is_hex else "--", tcell,
                            dcell(date), env[m]]) + " \\\\"]

    models = DECISION_MODELS + ["comparator-open"]
    # second revision: the larger comparator (both readouts, one checkpoint) and the untuned
    # backbones, from the same manifest; their runtimes are the pins of
    # build_revision2_notebook.py
    src2 = open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                             "build_revision2_notebook.py"), encoding="utf-8").read()
    vllm2 = re.findall(r'^VLLM_VERSION = "([\d.]+)"', src2, re.M)
    bbpk = re.findall(r'"torch==([\d.]+)", "transformers==([\d.]+)"', src2)
    assert len(vllm2) == 1 and len(bbpk) == 1, (vllm2, bbpk)
    extra = [("comparator-open2", "comparator-open2-ll"), "Qwen3.6-27B, both readouts",
             _tt(AD.COMPARATOR2_REPO), _tt("vllm " + vllm2[0])]
    bb_rows = [(t, AD.BACKBONE_REPOS[t]) for t in ("backbone-qwen35-0.8b-base",
               "backbone-qwen35-2b-base", "backbone-qwen35-9b-base", "backbone-qwen35-9b")]
    bbenv = _tt("torch " + bbpk[0][0]) + ", " + _tt("transformers " + bbpk[0][1])

    def row2(tags, name, repo_cell, env_cell, tcells):
        revs = {_single(man[t]["revision"], "revision", t) for t in tags}
        dates = {_dates(man[t]["run_date"]) for t in tags}
        assert len(revs) == 1 and len(dates) == 1, (tags, revs, dates)
        rev = revs.pop()
        assert re.fullmatch(r"[0-9a-f]{40}", rev), rev
        return " & ".join([name, repo_cell, _tt(rev[:10]), tcells, dcell(dates.pop()),
                           env_cell]) + " \\\\"

    for t in extra[0] + tuple(t for t, _r in bb_rows):
        temp = _single(man[t]["served_temperature"], "served_temperature", t)
        want = "m.comparator.temp" if t == "comparator-open2" else "m.likelihood.temp"
        assert abs(float(temp) - printed(want)) < 1e-9, (t, temp)
    spec = colspec([("P", 0.175), ("P", 0.275), ("P", 0.105), ("N", 0.06), ("P", 0.105),
                    ("P", 0.28)])
    lines = EAAI_HEADER + [
        "\\tablestylewide",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hd{Model} & \\hd{Repository or service} & \\hd{Revision} & \\hd{Temp.}"
        " & \\hd{Run date} & \\hd{Runtime} \\\\",
        "\\midrule"]
    lines += family_rows(models, 6, row)
    lines = [l.replace("{Generative comparator}", "{Generative comparators}") for l in lines]
    lines.append(row2(extra[0], "\\msw{comptwo}" + extra[1], extra[2], extra[3],
                      ecell("m.comparator.temp") + ", " + ecell("m.likelihood.temp")))
    # fourth revision: the thinking mode of the same checkpoint (sampled, adapters.THINK_SAMPLING)
    # and two further comparators in bf16 on the A100, with the vLLM pin the fourth notebook asserts
    assert abs(AD.THINK_SAMPLING["temperature"] - printed("m.think.temp")) < 1e-9
    src4 = open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                             "build_revision4_notebook.py"), encoding="utf-8").read()
    assert 'R2.VLLM_VERSION == "%s"' % vllm2[0] in src4, vllm2
    lines.append(row2(("comparator-open2-think",), "\\msw{comptwothink}Qwen3.6-27B, thinking",
                      _tt(AD.COMPARATOR2_REPO), _tt("vllm " + vllm2[0]), ecell("m.think.temp")))
    for tags, sw, name, rp in (
            (("comparator-gemma", "comparator-gemma-ll"), "compgem", "Gemma-4-31B, both readouts",
             AD.COMPARATOR3_REPO),
            (("comparator-mistral", "comparator-mistral-ll"), "compmis",
             "Mistral-Small-24B, both readouts", AD.COMPARATOR4_REPO)):
        for t in tags:
            temp = _single(man[t]["served_temperature"], "served_temperature", t)
            want = "m.likelihood.temp" if t.endswith("-ll") else "m.comparator.temp"
            assert abs(float(temp) - printed(want)) < 1e-9, (t, temp)
        lines.append(row2(tags, "\\msw{%s}%s" % (sw, name), _tt(rp),
                          _tt("vllm " + vllm2[0]) + ", bf16, eager",
                          ecell("m.comparator.temp") + ", " + ecell("m.likelihood.temp")))
    lines.append(groupspan(6, "Untuned backbones"))
    for t, r in bb_rows:
        lines.append(row2((t,), r.split("/")[1], _tt(r), bbenv,
                          ecell("m.likelihood.temp")))
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Revision is the start of the resolved commit of the weights and Temp.\\"
              " the served temperature that every answer record reports. The hosted service"
              " reports neither, and each response named the pinned model. Laya applies a"
              " temperature per question type and option count and records one as its nominal"
              " value. The comparators decode greedily or read key likelihoods at a temperature"
              " of one, except the thinking mode, which samples its reasoning at the temperature"
              " shown with a fixed seed. Qwen3.6-27B, Gemma-4-31B and Mistral-Small-24B ran on a"
              " Colab A100 GPU and every other open model on a Colab L4 GPU, and a pin written as"
              " a lower bound was resolved at install time.}"]
    return ewrite("t12_manifest.tex", lines)


def e_t13_gate():
    """Worked case, D2 CLINC-150 as an intent-routing gate. Rows are five policies: the
    hosted model answering every request, three models gated at the in-scope risk target
    with out-of-fold thresholds (rv.gate), and the held-out cascade this-that-model-1.0 to
    Jev (rv.cas). Quantities without a label print a dash; 'all' and 'none' are exact by
    construction (no reject option, no second stage)."""
    ALL, NONE = "all", "none"
    j, cas = "rv.gate.jev", "rv.cas.thisthat.jev.dtwo"

    def gated(m):
        g = f"rv.gate.{CN.SLUG[m]}"
        e5 = f"e5.{CN.SLUG[m]}.d2k150"
        return ["--", stack(ecell(f"{g}.cov"), f"{g}.cov"), ecell(f"{g}.risk"),
                ecell(f"{g}.riskub"), NONE, stack(ecell(f"{g}.far"), f"{g}.far"),
                ecell(f"{e5}.usd"), ecell(f"{e5}.pfifty"), ecell(f"{e5}.pninetyfive")]

    def pol(letter, m, text):
        return "(%s) %s%s" % (letter, mname(m), text)

    def casrow(letter, c, second):
        return [pol(letter, "this-that-1.0", " escalating to " + style.MODEL_LABELS[second]
                    .replace(", verbal", "")),
                stack(ecell(f"{c}.acc"), f"{c}.acc"), ALL, "--", "--",
                stack(ecell(f"{c}.esc"), f"{c}.esc"), ALL, ecell(f"{c}.usd"),
                ecell(f"{c}.pfifty"), ecell(f"{c}.pninetyfive")]

    e5j = "e5.jev.d2k150"
    groups = [
        ("Every request answered", [
            [pol("a", "jev-1.13.0", ", no gate"),
             stack(ecell("e1.jev.dtwo.acc"), "e1.jev.dtwo.acc"), ALL, "--", "--", NONE, ALL,
             ecell(f"{e5j}.usd"), ecell(f"{e5j}.pfifty"), ecell(f"{e5j}.pninetyfive")]]),
        ("Gate at the in-scope risk target", [
            [pol("b", "jev-1.13.0", "")] + gated("jev-1.13.0"),
            [pol("c", "kev-9b", "")] + gated("kev-9b"),
            [pol("d", "decider-2b", "")] + gated("decider-2b"),
            [pol("e", "comparator-open2-ll", "")] + gated("comparator-open2-ll"),
            [pol("f", "comparator-gemma", "")] + gated("comparator-gemma")]),
        ("Cascade", [casrow("g", cas, "jev-1.13.0"),
                     casrow("h", "rv.cas.thisthat.compgem.dtwo", "comparator-gemma")])]
    assert has(f"{j}.cov")
    spec = colspec([("P", 0.21), ("N", 0.1), ("N", 0.095), ("N", 0.075), ("N", 0.075),
                    ("N", 0.09), ("N", 0.105), ("N", 0.085), ("N", 0.075), ("N", 0.09)])
    lines = EAAI_HEADER + [
        "\\tablestylewide",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & \\hdgroup{five}{In-scope requests} & \\hdtop{Out of scope}"
        " & \\hdgroup{three}{Cost and latency} \\\\",
        "\\bandrules{2-6,7-7,8-10}",
        "\\headrow \\hdsub{Policy} & \\hdsub{Accuracy} & \\hdsub{Answered} & \\hdsub{Risk}"
        " & \\hdsub{Bound} & \\hdsub{Escalated} & \\hdsub{Accepted} & \\hdsub{USD}"
        " & \\hdsub{Median} & \\hdsub{\\num{p.pninetyfive}th pct.} \\\\",
        "\\midrule"]
    for g, rows in groups:
        lines.append(groupspan(10, g))
        for r in rows:
            lines.append(" & ".join(r) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Answered is the share of in-scope requests a policy answers without"
              " review, and Risk the error rate among them with its one-sided"
              " \\num{p.boot.level} percent upper bound. Escalated is the share sent to the"
              " second stage, and Accepted the share of out-of-scope requests routed to a"
              " handler, which is all of them when no request can be rejected. USD is the cost per thousand requests and the"
              " latencies are in ms per request, amortized over a batch for the comparators. The"
              " cascades have no reject option and so route every out-of-scope request, and their"
              " latencies compose recorded in-scope latencies offline. Beneath a value is"
              " its cluster bootstrap interval at \\num{p.boot.level} percent.}"]
    return ewrite("t13_gate.tex", lines)


def e_t18_oos_option():
    """Appendix. The intent benchmark with an explicit out-of-scope option (oo.*, a18): in-scope
    accuracy, the share of out-of-scope requests answered with the option and of in-scope
    requests wrongly answered with it, and the intent gate with the option and a held-out
    threshold (coverage and out-of-scope false acceptance with refit intervals) beside the
    false acceptance of the same gate without the option (rv.gate). Bold is the lowest false
    acceptance with the option among models that route at least half the in-scope requests."""
    models = [m for m in DECISION_MODELS + COMPARATORS_ALL if has(f"oo.{CN.SLUG[m]}.accin")]
    ok = [m for m in models if (printed(f"oo.{CN.SLUG[m]}.gcov") or 0) >= 0.5]
    best = best_of([f"oo.{CN.SLUG[m]}.gfar" for m in ok], "min")
    E_MARKS["t18_oos_option.tex"] = sorted(best)

    def row(m):
        ms = CN.SLUG[m]
        p = f"oo.{ms}"
        return [" & ".join([mname(m), ecell(f"{p}.accin"), ecell(f"{p}.oosrecall"),
                            ecell(f"{p}.falsereject"), stack(ecell(f"{p}.gcov"), f"{p}.gcov"),
                            stack(ecell(f"{p}.gfar", best), f"{p}.gfar"),
                            ecell(f"rv.gate.{ms}.far")]) + " \\\\"]

    spec = colspec([("P", NAME_W)] + [("N", (1 - NAME_W) / 6)] * 6)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & \\hdgroup{three}{Answers with the option}"
        " & \\hdgroup{three}{Gate at the in-scope risk target} \\\\",
        "\\bandrules{2-4,5-7}",
        "\\headrow \\hdsub{Model} & \\hdsub{In-scope acc.} & \\hdsub{OOS chosen}"
        " & \\hdsub{In-scope lost} & \\hdsub{Answered} & \\hdsub{Accepted}"
        " & \\hdsub{Without option} \\\\",
        "\\midrule"]
    lines += family_rows(models, 7, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{The \\num{n.d2k150.requests} CLINC-150 requests are asked with the"
              " \\num{p.kall} intents and one further option named out of scope. In-scope acc.\\ counts"
              " an in-scope request answered with that option as an error, OOS chosen is"
              " the share of out-of-scope requests answered with that option and In-scope lost the"
              " share of in-scope requests answered with it. The gate routes a request when it is"
              " not answered with the option and its top probability reaches a held-out threshold"
              " that targets \\num{p.riskfive} percent in-scope risk. Answered is its in-scope"
              " coverage and Accepted its out-of-scope false acceptance, beside the false"
              " acceptance of the same gate without the option, with cluster bootstrap intervals"
              " beneath Answered and Accepted. Laya (English) refused every request with this option set and is"
              " not listed. Bold marks the lowest false acceptance among models that answer at least"
              " half of the in-scope requests.}"]
    return ewrite("t18_oos_option.tex", lines)


def e_t19_new_tasks():
    """Main text. The two fourth-revision benchmarks (nt.*, a20): GoEmotions with rater-agreed
    Ekman labels and Banking77 with its 77 intents. Per benchmark accuracy, macro-F1, ECE as
    shipped and the paired difference from Jev in points, bold where Holm-adjusted p < 0.05.
    Rows: decision models, comparator readouts, and the classifiers trained on each benchmark's
    training split and the zero-shot entailment classifier."""
    models = DECISION_MODELS + COMPARATORS_ALL
    tasks = [("goemo", "GoEmotions, Ekman emotions"), ("banking", "Banking77 intents")]
    mets = [("acc", "max"), ("fone", "max"), ("ece", "min")]
    cls = [("BGE-small, trained per task", {"goemo": "bgegoemo", "banking": "bgebanking"}),
           ("DeBERTa-v3-large, fine-tuned", {"goemo": "debgoemo", "banking": "debbanking"}),
           ("DeBERTa-v3 NLI, zero-shot", {"goemo": "nlizs", "banking": "nlizs"})]
    best, sig = set(), set()
    for t, _l in tasks:
        slugs = [CN.SLUG[m] for m in models] + [d[t] for _n, d in cls]
        for met, mode in mets:
            best |= best_of([f"nt.{s}.{t}.{met}" for s in slugs], mode)
        for s in slugs:
            h = printed(f"nt.{s}.{t}.holm")
            if h is not None and h < HOLM_ALPHA:
                sig.add(f"nt.{s}.{t}.diff")
    E_MARKS["t19_new_tasks.tex"] = sorted(best | sig)

    def cells(slug_of):
        out = []
        for t, _l in tasks:
            p = f"nt.{slug_of(t)}.{t}"
            out += [ecell(f"{p}.{met}", best) for met, _m in mets]
            out.append(ecell(f"{p}.diff", sig) if has(f"{p}.diff") else "--")
        return out

    def row(m):
        ms = CN.SLUG[m]
        return [" & ".join([mname(m)] + cells(lambda t: ms)) + " \\\\"]

    spec = colspec([("P", NAME_W)] + [("N", (1 - NAME_W) / 8)] * 8)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{}" + "".join(" & \\hdgroup{four}{%s}" % l for _t, l in tasks)
        + " \\\\",
        "\\bandrules{2-5,6-9}",
        "\\headrow \\hdsub{Model}" + (" & \\hdsub{Acc.} & \\hdsub{F1} & \\hdsub{ECE}"
                                     " & \\hdsub{vs Jev}") * 2 + " \\\\",
        "\\midrule"]
    lines += family_rows(models, 9, row)
    lines.append("\\groupspan{nine}{Classifier trained on each benchmark's own labels}")
    for name, d in cls[:2]:
        lines.append(" & ".join([name] + cells(lambda t, d=d: d[t])) + " \\\\")
    lines.append("\\groupspan{nine}{Zero-shot classifier}")
    lines.append(" & ".join([cls[2][0]] + cells(lambda t: "nlizs")) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{GoEmotions has \\num{n.d3goemotions.requests} Reddit comments whose"
              " rater-agreed labels map to one of six Ekman emotions, and Banking77 has"
              " \\num{n.d2banking77.requests} queries, each asked with all 77 intents. F1 is"
              " macro-F1 in percent, ECE the calibration error as shipped, and vs Jev the paired"
              " accuracy difference from Jev 1.13.0 in points. The Kev checkpoints list Banking77"
              " among their training sets. Bold marks the best value in each of the first three"
              " columns of a benchmark and a difference significant after Holm correction at"
              " the five percent level.}"]
    return ewrite("t19_new_tasks.tex", lines)


VERBAL_READOUTS = ["comparator-open", "comparator-open2", "comparator-open2-think",
                   "comparator-gemma", "comparator-mistral"]


def e_t20_readouts():
    """Appendix. Reliability of the verbal readouts (vr.*, a17): per benchmark the share of
    decisions whose reply the fixed parser could not use (no parseable JSON, or keys written
    with their descriptions), the accuracy with the fixed parser and with a lenient re-parse
    that accepts such keys."""
    tasks = [("doneneutral", "D1"), ("dtwo", "D2"), ("emotion", "Emotion"),
             ("goemo", "GoEmo."), ("banking", "Bank.")]

    def row(m):
        ms = CN.SLUG[m]
        out = []
        for met in ("failshare", "accstrict", "acclenient"):
            out.append(" & ".join(
                [mname(m) if met == "failshare" else "",
                 {"failshare": "Unusable share", "accstrict": "Accuracy, fixed parser",
                  "acclenient": "Accuracy, lenient"}[met]]
                + [ecell(f"vr.{ms}.{t}.{met}") for t, _l in tasks]) + " \\\\")
        return out

    spec = colspec([("P", NAME_W), ("P", 0.215)] + [("N", 0.1)] * 5)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hd{Model} & \\hd{Measure}" + "".join(" & \\hd{%s}" % l for _t, l in tasks)
        + " \\\\",
        "\\midrule"]
    lines += family_rows(VERBAL_READOUTS, 7, row, between="\\addlinespace[2.5pt]")
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Unusable share counts decisions whose reply has no parseable JSON"
              " after any reasoning, or names an option by its key joined to its description."
              " The fixed parser, used in every other table, scores such a decision as a"
              " uniform distribution, and the lenient re-parse accepts a key followed by its"
              " description. GoEmo.\\ is GoEmotions and Bank.\\ is Banking77.}"]
    return ewrite("t20_readouts.tex", lines)


def e_t21_risk_control():
    """Appendix. Learn-then-test risk control (rc.*, a19): coverage with a finite-sample
    guarantee that the error rate of the accepted decisions stays at or below alpha with
    probability 1 - delta, and the realized risk on the accepted decisions."""
    models = DECISION_MODELS + COMPARATORS_ALL
    dsets = [("doneneutral", "D1 typed-decisions"), ("dtwo", "D2 CLINC-150")]
    best = set()
    for cs, _l in dsets:
        best |= best_of([f"rc.{CN.SLUG[m]}.{cs}.cov" for m in models], "max")
    E_MARKS["t21_risk_control.tex"] = sorted(best)

    def row(m):
        ms = CN.SLUG[m]
        cells = [mname(m)]
        for cs, _l in dsets:
            p = f"rc.{ms}.{cs}"
            cells += [ecell(f"{p}.cov", best), ecell(f"{p}.accepted"),
                      ecell(f"{p}.risk") if has(f"{p}.risk") else "--"]
        return [" & ".join(cells) + " \\\\"]

    spec = colspec([("P", NAME_W)] + [("N", (1 - NAME_W) / 6)] * 6)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{}" + "".join(" & \\hdgroup{three}{%s}" % l for _c, l in dsets)
        + " \\\\",
        "\\bandrules{2-4,5-7}",
        "\\headrow \\hdsub{Model}" + (" & \\hdsub{Coverage} & \\hdsub{Accepted}"
                                     " & \\hdsub{Risk}") * 2 + " \\\\",
        "\\midrule"]
    lines += family_rows(models, 7, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{The threshold is the lowest of \\num{rc.gridsize} fixed candidates"
              " whose accepted decisions on the calibration data pass an exact binomial test of"
              " an error rate at or below \\num{rc.alpha} percent, with a Bonferroni correction"
              " over the candidates at \\num{rc.confidence} percent confidence. Coverage and"
              " Risk are the accepted share and its error rate on the scored decisions, and"
              " Accepted counts those decisions, with a dash where none is accepted. Bold marks"
              " the highest coverage on each dataset, with ties bolded.}"]
    return ewrite("t21_risk_control.tex", lines)


def _body_labels(text):
    """\\num labels of a table file outside comments, header and note parameters (p.*)."""
    import re
    text = "\n".join(l for l in text.split("\n") if not l.lstrip().startswith("%"))
    labs = [l for l in re.findall(r"\\num\{([^}]+)\}", text) if not l.startswith("p.")]
    return sorted(labs), text.count("--")


# EAAI tables revised past their ACL counterparts: t04 prints a dash where a model has no
# raw arm, and t08 reads the revision cascades (rv.cas) instead of e6. They are exempt from
# the ACL cell check below; t09 to t13 have no ACL counterpart.
EAAI_DIVERGES = {"t03_headline.tex", "t04_calibration.tex", "t05_cardinality.tex",
                 "t06_names.tex", "t07_cost.tex", "t08_cascade.tex", "t11_paired.tex"}


def eaai_main():
    load_numbers()
    paths = [e_t03_headline(), e_t04_calibration(), e_t05_cardinality(), e_t06_names(),
             e_t07_cost(), e_t08_cascade(), e_t09_calib_tasks(), e_t10_selective(),
             e_t11_paired(), e_t12_manifest(), e_t13_gate(), e_t16_scores(),
             e_t17_backbones(), e_t18_oos_option(), e_t19_new_tasks(),
             e_t20_readouts(), e_t21_risk_control(), e_t22_cascade_qwen()]
    import re
    used = set()
    for p in paths:
        text = open(p, encoding="utf-8").read()
        used |= set(re.findall(r"\\num\{([^}]+)\}", text))
        used |= set(x for grp in re.findall(r"\\valbar\{([^}]+)\}\{([^}]+)\}\{([^}]*)\}", text)
                    for x in grp if x)
        # Every other EAAI table shows exactly the numeric labels and dashes of the ACL table.
        acl = os.path.join(TABLES_DIR, os.path.basename(p))
        if os.path.exists(acl) and os.path.basename(p) not in EAAI_DIVERGES:
            new, old = _body_labels(text), _body_labels(open(acl, encoding="utf-8").read())
            if new != old:
                raise SystemExit(f"{os.path.basename(p)}: numeric cells differ from the ACL"
                                 f" table ({len(new[0])} vs {len(old[0])} labels,"
                                 f" {new[1]} vs {old[1]} dashes)")
    missing = sorted(l for l in used if l not in NUM)
    if missing:
        raise SystemExit(f"{len(missing)} labels used in tables are not in numbers.json: "
                          f"{missing[:10]}")
    print(f"all {len(used)} distinct labels used in the EAAI tables exist in numbers.json,"
          " and every table with an ACL counterpart outside EAAI_DIVERGES shows its numeric"
          " cells")
    for name, labs in E_MARKS.items():
        print(f"  {name}: {len(labs)} bold or marked cells: {', '.join(labs)}")


def main():
    load_numbers()
    paths = [t03_headline(), t04_calibration(), t05_cardinality(), t06_names(), t07_cost(),
             t08_cascade()]
    import re
    used = set()
    for p in paths:
        text = open(p, encoding="utf-8").read()
        used |= set(re.findall(r"\\num\{([^}]+)\}", text))
    missing = sorted(l for l in used if l not in NUM)
    if missing:
        raise SystemExit(f"{len(missing)} labels used in tables are not in numbers.json: "
                          f"{missing[:10]}")
    print(f"all {len(used)} distinct \\num labels used in tables exist in numbers.json")


if __name__ == "__main__":
    import sys
    if "--eaai" in sys.argv[1:]:
        eaai_main()
    else:
        main()
