"""Write the LaTeX tabular bodies for Paper 4A from results/numbers.json.

Every number in these tables is a \\num{label} macro defined by collect_numbers.py,
never a literal, so run that script first (and after any label change). A model
row with no data for a given cell prints an en dash, and every table lists every
model in style.MODEL_COLORS order, so the tables do not change shape as open-model
results land; only their dashes fill in.

Output: ./tables/ (set TABLES_DIR to change)
"""
import json
import os

import collect_numbers as CN
import common as C
import style

TABLES_DIR = os.environ.get("TABLES_DIR", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "tables"))
MODEL_ORDER = list(style.MODEL_COLORS)
DECISION_MODELS = [m for m in MODEL_ORDER if not m.startswith("comparator")]

D3_TASKS = [("d3_conv_go_awry", "toxicity", "Tox."), ("d3_wiki_corpus", "power", "Pwr."),
            ("d3_emotion", "emotion", "Emo."), ("d3_wiki_politeness", "politeness", "Pol.")]
NAMES_DATASETS = [("d1", "done", "D1"), ("d3_conv_go_awry", "toxicity", "Tox."),
                   ("d3_wiki_corpus", "power", "Pwr.")]

# Abbreviated row labels for the narrow, single-column tables (t04, t06, t07), where
# style.MODEL_LABELS is too wide to fit one ACL column even with every dataset column
# abbreviated. t03 and t05 are table* (full width) and use the full labels.
SHORT_LABEL = {"jev-1.13.0": "Jev", "laya-en": "Laya-EN", "laya-ml": "Laya-ML",
               "kev-0.8b": "Kev-S", "kev-9b": "Kev-L", "decider-2b": "Decider",
               "this-that-1.0": "ThisThat", "nimble-9b": "Nimble",
               "comparator-open": "Comp-open"}

NUM = None


def load_numbers():
    global NUM
    p = os.path.join(C.RESULTS, "numbers.json")
    NUM = json.load(open(p, encoding="utf-8"))


def has(label):
    return label in NUM and NUM[label].get("value") is not None


def cell(label):
    return "\\num{%s}" % label if has(label) else "--"


def write(name, lines):
    os.makedirs(TABLES_DIR, exist_ok=True)
    path = os.path.join(TABLES_DIR, name)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"  wrote {path}")
    return path


HEADER = ["% Generated by shared/src/t01_tables.py. Do not edit by hand.",
          "% Every numeric cell is a num-macro from numbers.tex; -- means that",
          "% model has no result for this cell yet."]


def t03_headline():
    """table*, ten columns: model, D1, D2, the four D3 tasks, D3 macro-F1, D1 soft,
    D2 out-of-scope AUROC."""
    d3_header = " & ".join(lab for _c, _s, lab in D3_TASKS)
    lines = HEADER + [
        "% Intended environment: table* (full ACL text width), \\small, booktabs.",
        "\\begin{tabular}{lccccccccc}",
        "\\toprule",
        f"Model & D1 & D2 & {d3_header} & D3 F1 & D1 soft & D2 AUROC \\\\",
        "\\midrule"]
    for m in DECISION_MODELS + ["comparator-open"]:
        ms = CN.SLUG[m]
        row = [style.MODEL_LABELS[m], cell(f"e1.{ms}.doneneutral.acc"), cell(f"e1.{ms}.dtwo.acc")]
        for _cond, cslug, _lab in D3_TASKS:
            row.append(cell(f"e1.{ms}.{cslug}.acc"))
        row.append(cell(f"e1.{ms}.dthree.macrofone"))
        row.append(cell(f"e1.{ms}.doneneutral.softacc"))
        row.append(cell(f"e1.{ms}.oos.auroc"))
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return write("t03_headline.tex", lines)


def t04_calibration():
    """One ACL column, six columns: model, dataset, ECE shipped/raw/scaled, coverage
    at 5% risk. Rows are model by dataset (D1, D2, D3 pooled) rather than one wide
    row per model, so it fits one column at \\small."""
    lines = HEADER + [
        "% Intended environment: single column, \\small, booktabs.",
        "% Model column uses the abbreviations of t01_tables.SHORT_LABEL; spell them",
        "% out once in the caption, e.g. Kev-S/Kev-L for Kev-0.8B/Kev-9B. Ship, Raw,",
        "% Scal. and Cov5 are ECE shipped/raw/scaled and coverage at 5% risk.",
        "{\\setlength{\\tabcolsep}{3pt}",
        "\\begin{tabular}{llrrrr}",
        "\\toprule",
        "Model & Set & Ship & Raw & Scal. & Cov5 \\\\",
        "\\midrule"]
    dsets = [("doneneutral", "D1"), ("dtwo", "D2"), ("dthree", "D3")]
    for m in DECISION_MODELS + ["comparator-open"]:
        ms = CN.SLUG[m]
        for dslug, dlab in dsets:
            p = f"e1.{ms}.{dslug}"
            row = [SHORT_LABEL[m], dlab, cell(f"{p}.ece"), cell(f"{p}.eceraw"),
                   cell(f"{p}.ecescaled"), cell(f"{p}.covfive")]
            lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}}"]
    return write("t04_calibration.tex", lines)


def t05_cardinality():
    """table*, eight columns: model, accuracy at K in (5, 20, 50, 150), ECE at 150,
    hierarchical accuracy, and the accuracy drop from 5 to 150 options."""
    lines = HEADER + [
        "% Intended environment: table* (full ACL text width), \\small, booktabs.",
        "\\begin{tabular}{lccccccc}",
        "\\toprule",
        "Model & Acc.\\,5 & Acc.\\,20 & Acc.\\,50 & Acc.\\,150 & ECE\\,150 & Hier. & Drop \\\\",
        "\\midrule"]
    for m in DECISION_MODELS:
        ms = CN.SLUG[m]
        p = f"e3.{ms}"
        row = [style.MODEL_LABELS[m], cell(f"{p}.five.acc"), cell(f"{p}.twenty.acc"),
               cell(f"{p}.fifty.acc"), cell(f"{p}.all.acc"), cell(f"{p}.all.ece"),
               cell(f"{p}.hier.acc"), cell(f"{p}.drop")]
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return write("t05_cardinality.tex", lines)


def t06_names():
    """One ACL column, seven columns: model, dataset, flips per hundred for 0/1,
    random strings and swapped, the aligned AUC, and the test-retest floor."""
    lines = HEADER + [
        "% Intended environment: single column, \\small, booktabs.",
        "% Model column uses the abbreviations of t01_tables.SHORT_LABEL.",
        "{\\setlength{\\tabcolsep}{3pt}",
        "\\begin{tabular}{llrrrrr}",
        "\\toprule",
        "Model & Set & 0/1 & Rand. & Swap & AUC & Floor \\\\",
        "\\midrule"]
    for m in DECISION_MODELS:
        ms = CN.SLUG[m]
        for _cond, dslug, dlab in NAMES_DATASETS:
            p = f"e2.{ms}.{dslug}"
            row = [SHORT_LABEL[m], dlab, cell(f"{p}.k01.flips"), cell(f"{p}.krand.flips"),
                   cell(f"{p}.kswap.flips"), cell(f"{p}.kny.auc"), cell(f"{p}.floor")]
            lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}}"]
    return write("t06_names.tex", lines)


def t07_cost():
    """One ACL column, five columns: model, hardware, USD per 1,000 decisions,
    p50 and p95 latency in ms, all on d1_neutral."""
    lines = HEADER + [
        "% Intended environment: single column, \\small, booktabs.",
        "% Model column uses the abbreviations of t01_tables.SHORT_LABEL.",
        "{\\setlength{\\tabcolsep}{3pt}",
        "\\begin{tabular}{llrrr}",
        "\\toprule",
        "Model & Hardware & USD/1k & p50 ms & p95 ms \\\\",
        "\\midrule"]
    for m in DECISION_MODELS + ["comparator-open"]:
        ms = CN.SLUG[m]
        p = f"e5.{ms}.d1neutral"
        hw = "API" if m == "jev-1.13.0" else "Colab GPU"
        row = [SHORT_LABEL[m], hw if has(f"{p}.pfifty") else "--", cell(f"{p}.usd"),
               cell(f"{p}.pfifty"), cell(f"{p}.pninetyfive")]
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}}"]
    return write("t07_cost.tex", lines)


def t08_cascade():
    """Confidence-gated cascades on D1 (typed-decisions) and D2 (CLINC-150): every decision
    model first with the open generative comparator second, then every open decision model
    first with the hosted model second. Columns are the two single-stage accuracies, the
    best cascade accuracy over the threshold sweep, the escalated share at that point and
    its cost fraction (Equation costfraction)."""
    lines = HEADER + [
        r"% Intended environment: table* (full width), \small, booktabs.",
        r"{\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{llrrrrrrrrrr}",
        r"\toprule",
        r" & & \multicolumn{5}{c}{D1 typed-decisions} & \multicolumn{5}{c}{D2 CLINC-150} \\",
        r"\cmidrule(lr){3-7}\cmidrule(lr){8-12}",
        r"First & Second & First & Second & Cascade & Esc. & Cost & First & Second & Cascade & Esc. & Cost \\",
        r"\midrule"]
    pairs = [(m, "comparator-open") for m in MODEL_ORDER if m != "comparator-open"]
    pairs += [(m, "jev-1.13.0") for m in MODEL_ORDER if m not in ("jev-1.13.0", "comparator-open")]
    for f, s2 in pairs:
        fs, ss = CN.SLUG[f], CN.SLUG[s2]
        row = [SHORT_LABEL[f], SHORT_LABEL[s2]]
        for cs in ("doneneutral", "dtwo"):
            p = f"e6.{fs}.{ss}.{cs}"
            for m in ("accfirst", "accsecond", "hoacc", "hoescalated", "hocostfraction"):
                row.append(cell(f"{p}.{m}"))
        lines.append(" & ".join(row) + r" \\")
        if (f, s2) == pairs[len(DECISION_MODELS) - 1]:
            lines.append(r"\midrule")
    lines += [r"\bottomrule", r"\end{tabular}}"]
    return write("t08_cascade.tex", lines)


# ----------------------------------------------------------------------------------------
# EAAI mode (python t01_tables.py --eaai). Writes the redesigned tables of the journal
# version to EAAI_TABLES_DIR in the visual system of paper4a_tables.sty: a green header
# band, family group rows, model swatches in the figure palette, bold best values and
# symbol markers computed here from numbers.json at printed precision. Every numeric
# cell shows the same \num label as the ACL table of the same name; eaai_main() checks
# that against the ACL files before it returns. The default mode above is unchanged.

EAAI_TABLES_DIR = os.environ.get("EAAI_TABLES_DIR", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "tables_eaai"))

FAMILIES = [("Hosted", ["jev-1.13.0"]),
            ("Open, encoder head", ["laya-en", "laya-ml"]),
            ("Open, decoder head", ["kev-0.8b", "kev-9b", "decider-2b", "this-that-1.0",
                                    "nimble-9b"]),
            ("Generative comparator", ["comparator-open"])]
WORDS = {2: "two", 3: "three", 4: "four", 5: "five", 6: "six", 7: "seven", 8: "eight",
         9: "nine", 10: "ten", 11: "eleven", 12: "twelve", 13: "thirteen"}

EAAI_HEADER = ["% Generated by shared/src/t01_tables.py --eaai. Do not edit by hand.",
               "% Every numeric cell is a num-macro from numbers.tex; -- means that",
               "% model has no result for this cell yet. Needs paper4a_tables.sty."]


def printed(label):
    """The value of a label as the manuscript prints it, as a float, or None."""
    if not has(label):
        return None
    rec = NUM[label]
    v = rec["value"]
    if isinstance(v, str):
        return None
    fmt = rec.get("fmt")
    return float(format(v, fmt)) if fmt else float(v)


def best_of(labels, mode):
    """Labels holding the best printed value (max or min); ties are all returned."""
    vals = {l: printed(l) for l in labels}
    vals = {l: v for l, v in vals.items() if v is not None}
    if not vals:
        return set()
    b = max(vals.values()) if mode == "max" else min(vals.values())
    return {l for l, v in vals.items() if v == b}


def ecell(label, best=(), mark=None, slot=False):
    """A numeric cell: \\num{label}, bold when best, with an optional marker slot."""
    if not has(label):
        s = "--"
    else:
        s = "\\num{%s}" % label
        if label in best:
            s = "\\best{%s}" % s
    if slot:
        s += "\\mk{%s}" % (mark or "")
    return s


def mname(m):
    return "\\msw{%s}%s" % (CN.SLUG[m], style.MODEL_LABELS[m])


def groupspan(ncols, label):
    return "\\groupspan{%s}{%s}" % (WORDS[ncols], label)


def colspec(parts):
    """parts: list of (type, fraction). The fractions must sum to one, so the band and
    the rules span \\linewidth exactly."""
    total = sum(f for _t, f in parts)
    assert abs(total - 1.0) < 1e-9, total
    return "".join("%s{%.4f}" % (t, f) for t, f in parts)


def ewrite(name, lines):
    os.makedirs(EAAI_TABLES_DIR, exist_ok=True)
    path = os.path.join(EAAI_TABLES_DIR, name)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"  wrote {path}")
    return path


def family_rows(models, ncols, row_fn, between=None):
    """Group rows by model family, skipping families with no model in `models`;
    `between` is a line put between two models of the same family."""
    out = []
    for fam, members in FAMILIES:
        ms = [m for m in members if m in models]
        if not ms:
            continue
        out.append(groupspan(ncols, fam))
        for i, m in enumerate(ms):
            if between and i:
                out.append(between)
            out += row_fn(m)
    return out


def e_t03_headline():
    """Full width. Columns grouped by dataset: D1 (accuracy, soft accuracy), D2 (accuracy,
    out-of-scope AUROC), D3 (four task accuracies, mean macro-F1). Bold is the best value
    of each column over every row."""
    models = DECISION_MODELS + ["comparator-open"]
    cols = [("acc", "doneneutral.acc"), ("soft", "doneneutral.softacc"),
            ("acc", "dtwo.acc"), ("auroc", "oos.auroc")]
    cols += [("acc", f"{cs}.acc") for _c, cs, _l in D3_TASKS] + [("f1", "dthree.macrofone")]
    best = set()
    for _k, suf in cols:
        best |= best_of([f"e1.{CN.SLUG[m]}.{suf}" for m in models], "max")

    def row(m):
        ms = CN.SLUG[m]
        return [" & ".join([mname(m)] + [ecell(f"e1.{ms}.{suf}", best) for _k, suf in cols])
                + " \\\\"]

    spec = colspec([("P", 0.205)] + [("N", 0.795 / 9)] * 9)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & \\hdgroup{two}{D1 typed-decisions} & \\hdgroup{two}{D2 CLINC-150}"
        " & \\hdgroup{five}{D3 social science tasks} \\\\",
        "\\bandrules{2-3,4-5,6-10}",
        "\\headrow \\hdsub{Model} & \\hdsub{Acc.} & \\hdsub{Soft} & \\hdsub{Acc.} & \\hdsub{AUROC}"
        " & \\hdsub{Derail.} & \\hdsub{Power} & \\hdsub{Emotion} & \\hdsub{Polite.}"
        " & \\hdsub{F1} \\\\",
        "\\midrule"]
    lines += family_rows(models, 10, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Acc.\\ is accuracy, Soft is agreement with the teacher distribution,"
              " AUROC separates in-scope from out-of-scope inputs, and F1 is the mean macro-F1"
              " of the four D3 tasks in percent. Bold marks the best value in each column,"
              " with ties bolded.}"]
    return ewrite("t03_headline.tex", lines)


def e_t04_calibration():
    """Full width, one row per model, a column group per dataset with ECE shipped, raw and
    scaled and coverage at the stated risk. Bold is the lowest ECE and the highest coverage
    of each column; a triangle marks a shipped ECE above the raw ECE, where the stored
    temperature raises the error."""
    models = DECISION_MODELS + ["comparator-open"]
    dsets = ["doneneutral", "dtwo", "dthree"]
    metrics = [("ece", "min"), ("eceraw", "min"), ("ecescaled", "min"), ("covfive", "max")]
    best = set()
    for ds in dsets:
        for met, mode in metrics:
            # the raw arm exists only where rv.raw.<model>.available says so (a09 section C)
            pool = [m for m in models if met != "eceraw" or raw_ok(m)]
            best |= best_of([f"e1.{CN.SLUG[m]}.{ds}.{met}" for m in pool], mode)

    def row(m):
        ms = CN.SLUG[m]
        cells = [mname(m)]
        for ds in dsets:
            p = f"e1.{ms}.{ds}"
            # the marker compares unrounded values, so a rise hidden by rounding still shows
            ship = NUM[f"{p}.ece"]["value"] if printed(f"{p}.ece") is not None else None
            raw = (NUM[f"{p}.eceraw"]["value"]
                   if raw_ok(m) and printed(f"{p}.eceraw") is not None else None)
            up = ship is not None and raw is not None and ship > raw
            cells.append(ecell(f"{p}.ece", best, "\\mkup" if up else None, slot=True))
            cells += [ecell(f"{p}.eceraw", best) if raw_ok(m) else "--",
                      ecell(f"{p}.ecescaled", best), ecell(f"{p}.covfive", best)]
        return [" & ".join(cells) + " \\\\"]

    rest = (1.0 - 0.196 - 3 * 0.072) / 9
    spec = colspec([("P", 0.196)] + ([("N", 0.072)] + [("N", rest)] * 3) * 3)
    lines = EAAI_HEADER + [
        "\\tablestylewide",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & \\hdgroup{four}{D1 typed-decisions} & \\hdgroup{four}{D2 CLINC-150}"
        " & \\hdgroup{four}{D3 pooled} \\\\",
        "\\bandrules{2-5,6-9,10-13}",
        "\\headrow \\hdsub{Model}" + (" & \\hdsub{Ship.\\mk{}} & \\hdsub{Raw} & \\hdsub{Scal.}"
                                     " & \\hdsub{Cov.}") * 3 + " \\\\",
        "\\midrule"]
    lines += family_rows(models, 13, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Ship., Raw and Scal.\\ are the expected calibration error as shipped,"
              " at a temperature of one and after scaling, and Cov.\\ is the coverage at"
              " \\num{p.riskfive} percent risk as shipped. The raw arm exists only where the"
              " served temperature is known and the temperature-one distribution is stored,"
              " so Jev 1.13.0 and the generative comparator have none. Bold marks the lowest"
              " error and the highest coverage in each column, with ties bolded, and \\mkup\\"
              " marks a shipped error above the raw error before rounding, where the stored"
              " temperature raises the error.}"]
    return ewrite("t04_calibration.tex", lines)


def raw_ok(m):
    """True when the model has a raw (temperature-one) arm, per rv.raw.<model>.available."""
    lab = f"rv.raw.{CN.SLUG[m]}.available"
    return has(lab) and NUM[lab]["value"] == "yes"


def e_t05_cardinality():
    """Full width, one row per decision model: one-stage accuracy at the four option counts,
    ECE with all options, the exact two-stage accuracy and the drop from the smallest to
    the largest option set."""
    cols = [("five.acc", "max"), ("twenty.acc", "max"), ("fifty.acc", "max"),
            ("all.acc", "max"), ("all.ece", "min"), ("hier.acc", "max"), ("drop", "min")]
    best = set()
    for suf, mode in cols:
        best |= best_of([f"e3.{CN.SLUG[m]}.{suf}" for m in DECISION_MODELS], mode)

    def row(m):
        ms = CN.SLUG[m]
        return [" & ".join([mname(m)] + [ecell(f"e3.{ms}.{suf}", best) for suf, _m in cols])
                + " \\\\"]

    spec = colspec([("P", 0.23)] + [("N", 0.77 / 7)] * 7)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & \\hdgroup{four}{One-stage accuracy by option count}"
        " & \\hdgroup{three}{With all \\num{p.kall} options} \\\\",
        "\\bandrules{2-5,6-8}",
        "\\headrow \\hdsub{Model} & \\hdsub{\\num{p.kfive}} & \\hdsub{\\num{p.ktwenty}}"
        " & \\hdsub{\\num{p.kfifty}} & \\hdsub{\\num{p.kall}} & \\hdsub{ECE}"
        " & \\hdsub{Two-stage} & \\hdsub{Drop} \\\\",
        "\\midrule"]
    lines += family_rows(DECISION_MODELS, 8, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Two-stage is the accuracy of asking the domain and then the"
              " intent, and Drop is the one-stage accuracy lost from \\num{p.kfive} to"
              " \\num{p.kall} options. Bold marks the highest accuracy and the lowest error"
              " and drop in each column, with ties bolded.}"]
    return ewrite("t05_cardinality.tex", lines)


def flip_glyph(flips, floor):
    """Three-level scale of flips in excess of the test-retest floor, per hundred decisions:
    below one (the order of the hosted model's own floor), one to ten, ten or more."""
    if flips is None:
        return ""
    excess = round(flips - (floor or 0.0), 1)    # flips and floors print to one decimal
    if excess < 1.0:
        return "\\symnone"
    if excess < 10.0:
        return "\\symhalf"
    return "\\symfull"


def e_t06_names():
    """Full width, one block of three rows (the binary sets) per decision model: flips per
    hundred against the aligned identifiers for digits, random strings and the swap, each
    with a glyph for its excess over the floor, the aligned AUC and the floor."""
    set_names = {"done": "Typed-decisions", "toxicity": "Derailment", "power": "Power"}
    best = set()
    for _c, ds, _l in NAMES_DATASETS:
        best |= best_of([f"e2.{CN.SLUG[m]}.{ds}.kny.auc" for m in DECISION_MODELS], "max")

    def row(m):
        ms = CN.SLUG[m]
        out = []
        for i, (_c, ds, _l) in enumerate(NAMES_DATASETS):
            p = f"e2.{ms}.{ds}"
            floor = printed(f"{p}.floor")
            cells = [mname(m) if i == 0 else "", set_names[ds]]
            for k in ("k01", "krand", "kswap"):
                lab = f"{p}.{k}.flips"
                cells.append("\\flipcell{%s}{%s}" % (flip_glyph(printed(lab), floor), ecell(lab))
                             if has(lab) else "\\flipcell{}{--}")
            cells += [ecell(f"{p}.kny.auc", best), ecell(f"{p}.floor")]
            out.append(" & ".join(cells) + " \\\\")
        return out

    spec = colspec([("P", 0.24), ("P", 0.18)] + [("N", 0.12)] * 3 + [("N", 0.11)] * 2)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & \\hdtop{} & \\hdgroup{three}{Flips per hundred decisions}"
        " & \\hdtop{} & \\hdtop{} \\\\",
        "\\bandrules{3-5}",
        "\\headrow \\hdsub{Model} & \\hdsub{Binary set} & \\hdsub{\\flipcell{}{Digits}}"
        " & \\hdsub{\\flipcell{}{Random}} & \\hdsub{\\flipcell{}{Swapped}} & \\hdsub{AUC}"
        " & \\hdsub{Floor} \\\\",
        "\\midrule"]
    lines += family_rows(DECISION_MODELS, 7, row, between="\\addlinespace[2.5pt]")
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Digits, Random and Swapped are the option-name conditions, AUC is"
              " measured under the aligned identifiers and Floor is the test-retest floor. The"
              " glyph grades the flips above the model's floor on that set, \\symnone\\ below"
              " one per hundred, \\symhalf\\ from one to ten and \\symfull\\ ten or more,"
              " where a floor that was not measured counts as zero, as it is for every open"
              " model on typed-decisions. Bold marks the highest AUC on each set, with ties bolded.}"]
    return ewrite("t06_names.tex", lines)


def e_t07_cost():
    """Full width: platform, cost per thousand decisions with an inline bar on a linear
    scale to the most expensive model and a tick at the hosted list price, and the median
    and tail latency. Bold is the lowest value of each column."""
    models = DECISION_MODELS + ["comparator-open"]
    usd = [f"e5.{CN.SLUG[m]}.d1neutral.usd" for m in models]
    best = best_of(usd, "min")
    for suf in ("pfifty", "pninetyfive"):
        best |= best_of([f"e5.{CN.SLUG[m]}.d1neutral.{suf}" for m in models], "min")
    have = [l for l in usd if printed(l) is not None]
    top = max(have, key=printed)
    ref = "e5.jev.d1neutral.usd"

    def row(m):
        ms = CN.SLUG[m]
        p = f"e5.{ms}.d1neutral"
        hw = "API" if m == "jev-1.13.0" else "Colab GPU"
        bar = "\\valbar{%s.usd}{%s}{%s}" % (p, top, ref) if has(f"{p}.usd") else ""
        return [" & ".join([mname(m), hw if has(f"{p}.pfifty") else "--",
                            ecell(f"{p}.usd", best), bar, ecell(f"{p}.pfifty", best),
                            ecell(f"{p}.pninetyfive", best)]) + " \\\\"]

    bar_frac = 0.30
    spec = colspec([("P", 0.225), ("P", 0.13), ("N", 0.105), ("P", bar_frac),
                    ("N", 0.12), ("N", 0.12)])
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\setlength{\\valbarwidth}{\\dimexpr%.4f\\linewidth-2\\tabcolsep\\relax}" % bar_frac,
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & \\hdtop{} & \\hdgroup{two}{US dollars per thousand decisions}"
        " & \\hdgroup{two}{Latency in ms} \\\\",
        "\\bandrules{3-4,5-6}",
        "\\headrow \\hdsub{Model} & \\hdsub{Measured on} & \\hdsub{Cost} & \\hdsub{}"
        " & \\hdsub{Median} & \\hdsub{\\num{p.pninetyfive}th pct.} \\\\",
        "\\midrule"]
    lines += family_rows(models, 6, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Bars share one linear scale, and the orange tick marks the hosted"
              " model's cost at its list price. Bold marks the lowest value in each column, with ties bolded.}"]
    return ewrite("t07_cost.tex", lines)


def e_t08_cascade():
    """Full width, two stacked panels (D1 typed-decisions at decision level, D2 CLINC-150),
    one row per first stage grouped by the second stage. Cells come from rv.cas (a09 section
    D: out-of-fold thresholds, itemwise costs, cluster-bootstrap intervals that refit the
    thresholds). The single-stage accuracies are the e6 labels, which equal the
    acc_first/acc_second of revision_stats.json on the same aligned decisions (asserted
    below). A dot marks a gain whose interval excludes zero at printed precision."""
    rv = json.load(open(os.path.join(C.RESULTS, "revision_stats.json"), encoding="utf-8"))
    pairs = rv["D_cascades"]["pairs"]
    blocks = [("Escalation to the generative comparator", "comparator-open",
               [m for m in MODEL_ORDER if m != "comparator-open"]),
              ("Escalation to Jev 1.13.0", "jev-1.13.0",
               [m for m in MODEL_ORDER if m not in ("jev-1.13.0", "comparator-open")])]
    panels = [("D1 typed-decisions", "doneneutral", "d1_neutral"),
              ("D2 CLINC-150", "dtwo", "d2_k150")]
    spec = colspec([("P", 0.26), ("N", 0.085), ("N", 0.085), ("N", 0.085), ("P", 0.13),
                    ("N", 0.075), ("P", 0.11), ("N", 0.085), ("N", 0.085)])
    marked = []
    lines = EAAI_HEADER + ["\\tablestylewide"]
    for pi, (ptitle, cs, cond) in enumerate(panels):
        if pi:
            lines.append("\\par\\vspace{6pt}")
        lines += [
            "\\begin{tabular}{%s}" % spec,
            "\\toprule",
            "\\headrow \\hdtop{%s} & \\hdgroup{two}{Single stage}"
            " & \\hdgroup{four}{Cascade} & \\hdgroup{two}{Escalation} \\\\" % ptitle,
            "\\bandrules{2-3,4-7,8-9}",
            "\\headrow \\hdsub{First stage} & \\hdsub{First} & \\hdsub{Second}"
            " & \\hdsub{Accuracy} & \\hdsub{} & \\hdsub{Gain\\mk{}} & \\hdsub{}"
            " & \\hdsub{Esc.} & \\hdsub{Cost} \\\\",
            "\\midrule"]
        for label, second, firsts in blocks:
            lines.append(groupspan(9, label))
            for f in firsts:
                fs, ss = CN.SLUG[f], CN.SLUG[second]
                e6p, p = f"e6.{fs}.{ss}.{cs}", f"rv.cas.{fs}.{ss}.{cs}"
                key = f"{f}>{second}|{cond}"
                if key in pairs:
                    dl = pairs[key]["decision_level"]
                    for lab, ref in ((f"{e6p}.accfirst", dl["acc_first"]),
                                     (f"{e6p}.accsecond", dl["acc_second"])):
                        assert has(lab) and abs(NUM[lab]["value"] - ref) < 1e-12, lab
                lo, hi = printed(f"{p}.gainlo"), printed(f"{p}.gainhi")
                excl = lo is not None and hi is not None and (lo > 0 or hi < 0)
                if excl:
                    marked.append(p)
                cells = [mname(f), ecell(f"{e6p}.accfirst"), ecell(f"{e6p}.accsecond"),
                         ecell(f"{p}.acc"), ivcell(f"{p}.acc"),
                         ecell(f"{p}.gain", mark="\\symfull" if excl else None, slot=True),
                         ivcell(f"{p}.gain"), ecell(f"{p}.esc"), ecell(f"{p}.costfrac")]
                lines.append(" & ".join(cells) + " \\\\")
        lines += ["\\bottomrule", "\\end{tabular}"]
    mark_text = (" \\symfull\\ marks a gain whose interval excludes zero."
                 if marked else " No gain interval excludes zero.")
    lines += ["\\tablenote{First and Second are the accuracies of each stage alone, Accuracy is"
              " the cascade accuracy with thresholds chosen on data disjoint from the scored"
              " items, and Gain is its difference from the better single stage in points. Esc.\\"
              " is the escalated share and Cost the cost fraction from each decision's own"
              " cost, where the escalation unit on D1 is the decision, a request's cost is shared"
              " among its decisions and the comparator is charged per question. Brackets hold"
              " cluster bootstrap intervals at"
              " \\num{p.boot.level} percent whose \\num{p.boot.refitreps} replicates refit the"
              " thresholds, and" + mark_text[0].lower() + mark_text[1:] + "}"]
    E_MARKS["t08_cascade.tex"] = marked
    return ewrite("t08_cascade.tex", lines)


# Labels behind the bold cells and the markers of the new EAAI tables, for the report.
E_MARKS = {}


def ivcell(prefix, lo="lo", hi="hi"):
    """A muted interval [lo, hi] for a separate left-aligned column; empty when missing."""
    a, b = f"{prefix}{lo}", f"{prefix}{hi}"
    if not (has(a) and has(b)):
        return ""
    return "{\\scriptsize\\cellnote{[\\num{%s}, \\num{%s}]}}" % (a, b)


def stack(value_cell, prefix, lo="lo", hi="hi"):
    """A value with its muted interval on a second line of the same cell. The break is a new
    paragraph, so both lines keep the column's alignment (\\newline would add \\hfil and push
    the value to the left)."""
    iv = ivcell(prefix, lo, hi)
    return value_cell + ("\\par" + iv if iv and value_cell != "--" else "")


TASK_COLS = [("doneneutral", "D1"), ("dtwo", "D2"), ("toxicity", "Derail."),
             ("power", "Power"), ("emotion", "Emotion"), ("politeness", "Polite.")]


def e_t09_calib_tasks():
    """Per-task calibration: expected calibration error as shipped and after cross-fitted
    temperature scaling (rv.ts), with the refit bootstrap interval of the scaled error beneath
    it. Bold is the lowest shipped and the lowest scaled error of each column."""
    models = DECISION_MODELS + ["comparator-open"]
    best = set()
    for cs, _l in TASK_COLS:
        for met in ("ece", "ecescaled"):
            best |= best_of([f"rv.ts.{CN.SLUG[m]}.{cs}.{met}" for m in models], "min")
    E_MARKS["t09_calib_tasks.tex"] = sorted(best)

    def row(m):
        ms = CN.SLUG[m]
        cells = [mname(m)]
        for cs, _l in TASK_COLS:
            p = f"rv.ts.{ms}.{cs}"
            cells += [ecell(f"{p}.ece", best),
                      stack(ecell(f"{p}.ecescaled", best), f"{p}.ecescaled")]
        return [" & ".join(cells) + " \\\\"]

    spec = colspec([("P", 0.16)] + [("N", 0.047), ("Q", 0.093)] * 6)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\setlength{\\tabcolsep}{2pt}",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{}" + "".join(" & \\hdgroup{two}{%s}" % l for _c, l in TASK_COLS)
        + " \\\\",
        "\\bandrules{2-3,4-5,6-7,8-9,10-11,12-13}",
        "\\headrow \\hdsub{Model}" + " & \\hdsub{Ship.} & \\hdsub{Scaled}" * 6 + " \\\\",
        "\\midrule"]
    lines += family_rows(models, 13, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Ship.\\ is the expected calibration error as shipped and Scaled the"
              " error after temperature scaling, with one temperature per question type fitted"
              " on the calibration split for D1 and temperatures cross-fitted over item folds for"
              " the other tasks. Beneath each scaled error is its cluster bootstrap interval at"
              " \\num{p.boot.level} percent, whose \\num{p.boot.refitreps} replicates refit the"
              " temperatures. Bold marks the lowest error in each column, with ties bolded.}"]
    return ewrite("t09_calib_tasks.tex", lines)


def e_t10_selective():
    """Selective prediction at the lower risk target on D1 and D2: in-sample coverage with its
    bootstrap interval (rv.sel), and the held-out coverage, realized risk and its one-sided
    upper bound (rv.ho). Bold is the highest held-out coverage of each dataset."""
    models = DECISION_MODELS + ["comparator-open"]
    dsets = [("doneneutral", "D1 typed-decisions"), ("dtwo", "D2 CLINC-150")]
    best = set()
    for cs, _l in dsets:
        best |= best_of([f"rv.ho.{CN.SLUG[m]}.{cs}.five.cov" for m in models], "max")
    E_MARKS["t10_selective.tex"] = sorted(best)

    def row(m):
        ms = CN.SLUG[m]
        cells = [mname(m)]
        for cs, _l in dsets:
            s, h = f"rv.sel.{ms}.{cs}", f"rv.ho.{ms}.{cs}.five"
            cells += [stack(ecell(f"{s}.covfive"), f"{s}.covfive"), ecell(f"{h}.cov", best),
                      ecell(f"{h}.risk"), ecell(f"{h}.riskub")]
        return [" & ".join(cells) + " \\\\"]

    spec = colspec([("P", 0.2)] + [("N", 0.11), ("N", 0.1), ("N", 0.09), ("N", 0.1)] * 2)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{}" + "".join(" & \\hdgroup{four}{%s}" % l for _c, l in dsets)
        + " \\\\",
        "\\bandrules{2-5,6-9}",
        "\\headrow \\hdsub{Model}" + (" & \\hdsub{In-sample} & \\hdsub{Held-out}"
                                     " & \\hdsub{Risk} & \\hdsub{Bound}") * 2 + " \\\\",
        "\\midrule"]
    lines += family_rows(models, 9, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{In-sample is the coverage at \\num{p.riskfive} percent risk with the"
              " threshold chosen on the scored decisions, with its cluster bootstrap interval"
              " at \\num{p.boot.level} percent beneath. Held-out applies a threshold chosen by the"
              " same rule on the calibration split for D1 and on the other item folds for D2,"
              " Risk is the error rate of the decisions it accepts and Bound is the one-sided"
              " \\num{p.boot.level} percent Clopper-Pearson upper limit of that rate, with a"
              " dash where no decision is accepted, and a coverage printed as zero can still"
              " accept a few decisions. Bold marks the highest held-out coverage on"
              " each dataset, with ties bolded.}"]
    return ewrite("t10_selective.tex", lines)


HOLM_ALPHA = 0.05   # stated in words in the table note, never printed


def e_t11_paired():
    """Paired accuracy differences with Jev (rv.pd): each model minus Jev in points on
    identical decisions, with the paired cluster bootstrap interval beneath. Bold where the
    Holm-adjusted p value, at printed precision, is below HOLM_ALPHA."""
    models = [m for m in DECISION_MODELS if m != "jev-1.13.0"] + ["comparator-open"]
    sig = set()
    for m in models:
        for cs, _l in TASK_COLS:
            p = f"rv.pd.{CN.SLUG[m]}.{cs}"
            h = printed(f"{p}.holm")
            if h is not None and h < HOLM_ALPHA:
                sig.add(f"{p}.diff")
    E_MARKS["t11_paired.tex"] = sorted(sig)

    def row(m):
        ms = CN.SLUG[m]
        cells = [mname(m)]
        for cs, _l in TASK_COLS:
            p = f"rv.pd.{ms}.{cs}"
            cells.append(stack(ecell(f"{p}.diff", sig), f"{p}.diff"))
        return [" & ".join(cells) + " \\\\"]

    spec = colspec([("P", 0.22)] + [("N", 0.13)] * 6)
    lines = EAAI_HEADER + [
        "\\tablestyle",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & \\hdgroup{two}{Workflow and intent sets}"
        " & \\hdgroup{four}{D3 social science tasks} \\\\",
        "\\bandrules{2-3,4-7}",
        "\\headrow \\hdsub{Model}" + "".join(" & \\hdsub{%s}" % l for _c, l in TASK_COLS)
        + " \\\\",
        "\\midrule"]
    lines += family_rows(models, 7, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Each cell is the accuracy of the model minus that of Jev 1.13.0 on"
              " identical decisions in percentage points, with its paired cluster bootstrap"
              " interval at \\num{p.boot.level} percent over \\num{p.boot.pairedreps} replicates"
              " beneath. Bold marks a difference that is significant after Holm correction"
              " across the models of each dataset at the five percent level.}"]
    return ewrite("t11_paired.tex", lines)


MANIFEST_TEMP = {"jev-1.13.0": None, "laya-en": "m.laya.temp", "laya-ml": "m.laya.temp",
                 "kev-0.8b": "m.kev08b.temp", "kev-9b": "m.kev9b.temp",
                 "decider-2b": "m.decider.temp", "this-that-1.0": "m.thisthat.temp",
                 "nimble-9b": "m.nimble.temp", "comparator-open": "m.comparator.temp"}


def _tt(s):
    """Monospace identifier; a space inside it (package and version) does not break."""
    return "\\texttt{%s}" % s.replace("_", "\\_").replace(" ", "~")


def _single(counter, what, model):
    """The one value of a run_manifest field; the manifest must hold exactly one."""
    vals = list(counter)
    assert len(vals) == 1, f"{model}: {what} is not unique in run_manifest.json: {vals}"
    return json.loads(vals[0])


def e_t12_manifest():
    """Run manifest: repository or service identifier (adapters.py), resolved revision, served
    temperature and run date (results/run_manifest.json, one value per model, asserted), and
    the runtime with the package pins of build_notebook.py and the comparator's logged vLLM and
    torch versions. Identifiers, dates and versions are set in texttt, the served temperature
    is a num label."""
    import re
    import adapters as AD
    man = json.load(open(os.path.join(C.RESULTS, "run_manifest.json"), encoding="utf-8"))
    src = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "build_notebook.py"),
               encoding="utf-8").read()

    def pin(pat):
        v = sorted(set(re.findall(pat, src)))
        assert len(v) == 1, (pat, v)
        return v[0]
    torch = pin(r'"torch==([\d.]+)"')
    laya = pin(r'"laya==([\d.]+)"')
    tf_min = pin(r'"transformers>=([\d.]+),<\d+"')
    tf_pin = pin(r'"transformers==([\d.]+)"')
    thisthat_sha = pin(r'THISTHAT_SHA = "([0-9a-f]{40})"')
    log = open(os.path.join(C.ANSWERS, "comparator-open", "comparator_log.txt"),
               encoding="utf-8", errors="replace").read()
    vv = sorted(set(re.findall(r"^vllm (\S+) torch (\S+?)(?:\+\S+)?$", log, re.M)))
    assert len(vv) == 1, vv
    vllm, ctorch = vv[0]
    kev_sha = AD.KEV_GITHUB_COMMIT

    repo = {"jev-1.13.0": "TypeSafe API, model " + _tt("jev-1.13.0"),
            "laya-en": _tt(AD.LAYA_REPO),
            "laya-ml": _tt(AD.LAYA_REPO) + ", subfolder " + _tt("multilingual"),
            "kev-0.8b": _tt(AD.KEV_REPOS["kev-0.8b"]), "kev-9b": _tt(AD.KEV_REPOS["kev-9b"]),
            "decider-2b": _tt(AD.DECIDER_REPO), "this-that-1.0": _tt(AD.THISTHAT_REPO),
            "nimble-9b": _tt(AD.NIMBLE_REPO), "comparator-open": _tt(AD.COMPARATOR_REPO)}
    colab = ""   # every open model and the comparator ran on a Colab L4, stated in the note
    tfpin = ", " + _tt("transformers>=" + tf_min)
    torchkev = colab + _tt("torch " + torch) + ", " + _tt("kev@" + kev_sha[:10])
    env = {"jev-1.13.0": "hosted service through " + _tt("typesafe_sdk"),
           "laya-en": colab + _tt("laya " + laya) + ", " + _tt("torch " + torch),
           "laya-ml": colab + _tt("laya " + laya) + ", " + _tt("torch " + torch),
           "kev-0.8b": torchkev + tfpin, "kev-9b": torchkev + tfpin,
           "decider-2b": torchkev + tfpin,
           "this-that-1.0": torchkev + tfpin + ", " + _tt("thisthat@" + thisthat_sha[:10]),
           "nimble-9b": colab + _tt("torch " + torch) + ", " + _tt("transformers " + tf_pin),
           "comparator-open": colab + _tt("vllm " + vllm) + ", " + _tt("torch " + ctorch)}

    def row(m):
        d = man[m]
        rev = _single(d["revision"], "revision", m)
        date = _single(d["run_date"], "run_date", m)
        temp = _single(d["served_temperature"], "served_temperature", m)
        assert _single(d["model_returned"], "model_returned", m)
        tl = MANIFEST_TEMP[m]
        if tl is None:
            assert temp is None, m
            tcell = "--"
        else:
            assert temp is not None and abs(float(format(temp, NUM[tl]["fmt"] or ".2f"))
                                            - printed(tl)) < 1e-9, (m, temp)
            tcell = ecell(tl)
        is_hex = bool(re.fullmatch(r"[0-9a-f]{40}", str(rev)))
        assert is_hex or m == "jev-1.13.0", (m, rev)
        return [" & ".join([mname(m), repo[m], _tt(rev[:10]) if is_hex else "--", tcell,
                            _tt(date), env[m]]) + " \\\\"]

    models = DECISION_MODELS + ["comparator-open"]
    spec = colspec([("P", 0.175), ("P", 0.275), ("P", 0.105), ("N", 0.06), ("P", 0.105),
                    ("P", 0.28)])
    lines = EAAI_HEADER + [
        "\\tablestylewide",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hd{Model} & \\hd{Repository or service} & \\hd{Revision} & \\hd{Temp.}"
        " & \\hd{Run date} & \\hd{Runtime} \\\\",
        "\\midrule"]
    lines += family_rows(models, 6, row)
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Revision is the start of the resolved commit of the weights and Temp.\\"
              " the served temperature that every answer record reports. The hosted service"
              " reports neither, and each response named the pinned model. Laya applies a"
              " temperature per question type and option count and records one as its nominal"
              " value, and the comparator decodes greedily. Every open model and the comparator"
              " ran on a Colab L4 GPU, and a pin written as a lower bound was resolved at"
              " install time.}"]
    return ewrite("t12_manifest.tex", lines)


def e_t13_gate():
    """Worked case, D2 CLINC-150 as an intent-routing gate. Rows are five policies: the
    hosted model answering every request, three models gated at the in-scope risk target
    with out-of-fold thresholds (rv.gate), and the held-out cascade this-that-model-1.0 to
    Jev (rv.cas). Quantities without a label print a dash; 'all' and 'none' are exact by
    construction (no reject option, no second stage)."""
    ALL, NONE = "all", "none"
    j, cas = "rv.gate.jev", "rv.cas.thisthat.jev.dtwo"

    def gated(m):
        g = f"rv.gate.{CN.SLUG[m]}"
        e5 = f"e5.{CN.SLUG[m]}.d2k150"
        return ["--", stack(ecell(f"{g}.cov"), f"{g}.cov"), ecell(f"{g}.risk"),
                ecell(f"{g}.riskub"), NONE, stack(ecell(f"{g}.far"), f"{g}.far"),
                ecell(f"{e5}.usd"), ecell(f"{e5}.pfifty"), ecell(f"{e5}.pninetyfive")]

    def pol(letter, m, text):
        return "(%s) %s%s" % (letter, mname(m), text)

    e5j = "e5.jev.d2k150"
    groups = [
        ("Every request answered", [
            [pol("a", "jev-1.13.0", ", no gate"),
             stack(ecell("e1.jev.dtwo.acc"), "e1.jev.dtwo.acc"), ALL, "--", "--", NONE, ALL,
             ecell(f"{e5j}.usd"), ecell(f"{e5j}.pfifty"), ecell(f"{e5j}.pninetyfive")]]),
        ("Gate at the in-scope risk target", [
            [pol("b", "jev-1.13.0", "")] + gated("jev-1.13.0"),
            [pol("c", "kev-9b", "")] + gated("kev-9b"),
            [pol("d", "decider-2b", "")] + gated("decider-2b")]),
        ("Cascade", [
            [pol("e", "this-that-1.0", " escalating to Jev 1.13.0"),
             stack(ecell(f"{cas}.acc"), f"{cas}.acc"), ALL, "--", "--",
             stack(ecell(f"{cas}.esc"), f"{cas}.esc"), ALL, "--",
             ecell(f"{cas}.pfifty"), ecell(f"{cas}.pninetyfive")]])]
    assert has(f"{j}.cov")
    spec = colspec([("P", 0.21), ("N", 0.1), ("N", 0.095), ("N", 0.075), ("N", 0.075),
                    ("N", 0.09), ("N", 0.105), ("N", 0.085), ("N", 0.075), ("N", 0.09)])
    lines = EAAI_HEADER + [
        "\\tablestylewide",
        "\\begin{tabular}{%s}" % spec,
        "\\toprule",
        "\\headrow \\hdtop{} & \\hdgroup{five}{In-scope requests} & \\hdtop{Out of scope}"
        " & \\hdgroup{three}{Cost and latency} \\\\",
        "\\bandrules{2-6,7-7,8-10}",
        "\\headrow \\hdsub{Policy} & \\hdsub{Accuracy} & \\hdsub{Answered} & \\hdsub{Risk}"
        " & \\hdsub{Bound} & \\hdsub{Escalated} & \\hdsub{Accepted} & \\hdsub{USD}"
        " & \\hdsub{Median} & \\hdsub{\\num{p.pninetyfive}th pct.} \\\\",
        "\\midrule"]
    for g, rows in groups:
        lines.append(groupspan(10, g))
        for r in rows:
            lines.append(" & ".join(r) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\tablenote{Answered is the share of in-scope requests a policy answers without"
              " review, Risk the error rate among them with its one-sided \\num{p.boot.level}"
              " percent upper bound, Escalated the share sent to the second stage and Accepted"
              " the share of out-of-scope requests routed to a handler, which is all of them"
              " when no request can be rejected. USD is the cost per thousand requests and the"
              " latencies are in ms per request. The cascade answers in-scope requests at"
              " \\num{rv.cas.thisthat.jev.dtwo.costfrac} of the cost of Jev 1.13.0 alone, and"
              " its latencies compose recorded in-scope latencies offline. Beneath a value is"
              " its cluster bootstrap interval at \\num{p.boot.level} percent.}"]
    return ewrite("t13_gate.tex", lines)


def _body_labels(text):
    """\\num labels of a table file outside comments, header and note parameters (p.*)."""
    import re
    text = "\n".join(l for l in text.split("\n") if not l.lstrip().startswith("%"))
    labs = [l for l in re.findall(r"\\num\{([^}]+)\}", text) if not l.startswith("p.")]
    return sorted(labs), text.count("--")


# EAAI tables revised past their ACL counterparts: t04 prints a dash where a model has no
# raw arm, and t08 reads the revision cascades (rv.cas) instead of e6. They are exempt from
# the ACL cell check below; t09 to t13 have no ACL counterpart.
EAAI_DIVERGES = {"t04_calibration.tex", "t08_cascade.tex"}


def eaai_main():
    load_numbers()
    paths = [e_t03_headline(), e_t04_calibration(), e_t05_cardinality(), e_t06_names(),
             e_t07_cost(), e_t08_cascade(), e_t09_calib_tasks(), e_t10_selective(),
             e_t11_paired(), e_t12_manifest(), e_t13_gate()]
    import re
    used = set()
    for p in paths:
        text = open(p, encoding="utf-8").read()
        used |= set(re.findall(r"\\num\{([^}]+)\}", text))
        used |= set(x for grp in re.findall(r"\\valbar\{([^}]+)\}\{([^}]+)\}\{([^}]*)\}", text)
                    for x in grp if x)
        # Every other EAAI table shows exactly the numeric labels and dashes of the ACL table.
        acl = os.path.join(TABLES_DIR, os.path.basename(p))
        if os.path.exists(acl) and os.path.basename(p) not in EAAI_DIVERGES:
            new, old = _body_labels(text), _body_labels(open(acl, encoding="utf-8").read())
            if new != old:
                raise SystemExit(f"{os.path.basename(p)}: numeric cells differ from the ACL"
                                 f" table ({len(new[0])} vs {len(old[0])} labels,"
                                 f" {new[1]} vs {old[1]} dashes)")
    missing = sorted(l for l in used if l not in NUM)
    if missing:
        raise SystemExit(f"{len(missing)} labels used in tables are not in numbers.json: "
                          f"{missing[:10]}")
    print(f"all {len(used)} distinct labels used in the EAAI tables exist in numbers.json,"
          " and every table with an ACL counterpart outside EAAI_DIVERGES shows its numeric"
          " cells")
    for name, labs in E_MARKS.items():
        print(f"  {name}: {len(labs)} bold or marked cells: {', '.join(labs)}")


def main():
    load_numbers()
    paths = [t03_headline(), t04_calibration(), t05_cardinality(), t06_names(), t07_cost(),
             t08_cascade()]
    import re
    used = set()
    for p in paths:
        text = open(p, encoding="utf-8").read()
        used |= set(re.findall(r"\\num\{([^}]+)\}", text))
    missing = sorted(l for l in used if l not in NUM)
    if missing:
        raise SystemExit(f"{len(missing)} labels used in tables are not in numbers.json: "
                          f"{missing[:10]}")
    print(f"all {len(used)} distinct \\num labels used in tables exist in numbers.json")


if __name__ == "__main__":
    import sys
    if "--eaai" in sys.argv[1:]:
        eaai_main()
    else:
        main()
